CREATE TABLE IF NOT EXISTS cdp_warehouse_stream_pipeline (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    pipeline_key VARCHAR(128) NOT NULL,
    display_name VARCHAR(128) NOT NULL,
    source_type VARCHAR(32) NOT NULL,
    source_ref VARCHAR(256) NOT NULL,
    source_topic VARCHAR(256) DEFAULT NULL,
    consumer_group VARCHAR(128) DEFAULT NULL,
    processor_type VARCHAR(64) NOT NULL,
    sink_type VARCHAR(32) NOT NULL,
    sink_ref VARCHAR(256) NOT NULL,
    delivery_semantics VARCHAR(32) NOT NULL DEFAULT 'AT_LEAST_ONCE',
    checkpoint_interval_seconds INT NOT NULL DEFAULT 60,
    max_lag_ms BIGINT NOT NULL DEFAULT 600000,
    max_checkpoint_age_seconds INT NOT NULL DEFAULT 300,
    lifecycle_status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    owner_name VARCHAR(128) DEFAULT NULL,
    config_json JSON DEFAULT NULL,
    last_checkpoint_id VARCHAR(128) DEFAULT NULL,
    last_source_offset VARCHAR(256) DEFAULT NULL,
    last_committed_offset VARCHAR(256) DEFAULT NULL,
    last_watermark_time DATETIME DEFAULT NULL,
    last_checkpoint_at DATETIME DEFAULT NULL,
    last_lag_ms BIGINT DEFAULT NULL,
    last_runtime_status VARCHAR(32) DEFAULT NULL,
    last_status_message VARCHAR(1000) DEFAULT NULL,
    last_reported_by VARCHAR(128) DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_cdp_warehouse_stream_pipeline (tenant_id, pipeline_key),
    INDEX idx_cdp_warehouse_stream_pipeline_status (tenant_id, lifecycle_status, last_runtime_status),
    INDEX idx_cdp_warehouse_stream_pipeline_sink (tenant_id, sink_type, sink_ref),
    INDEX idx_cdp_warehouse_stream_pipeline_checkpoint (tenant_id, last_checkpoint_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CDP warehouse realtime stream pipeline contract and latest runtime state';

CREATE TABLE IF NOT EXISTS cdp_warehouse_stream_checkpoint (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    pipeline_key VARCHAR(128) NOT NULL,
    checkpoint_id VARCHAR(128) NOT NULL DEFAULT '',
    source_partition VARCHAR(128) NOT NULL DEFAULT '',
    source_offset VARCHAR(256) DEFAULT NULL,
    committed_offset VARCHAR(256) DEFAULT NULL,
    watermark_time DATETIME DEFAULT NULL,
    checkpoint_time DATETIME NOT NULL,
    lag_ms BIGINT DEFAULT NULL,
    row_count BIGINT NOT NULL DEFAULT 0,
    status VARCHAR(32) NOT NULL,
    error_message VARCHAR(1000) DEFAULT NULL,
    reported_by VARCHAR(128) DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uk_cdp_warehouse_stream_checkpoint (tenant_id, pipeline_key, checkpoint_id, source_partition),
    INDEX idx_cdp_warehouse_stream_checkpoint_time (tenant_id, pipeline_key, checkpoint_time),
    INDEX idx_cdp_warehouse_stream_checkpoint_status (tenant_id, status, checkpoint_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CDP warehouse realtime stream checkpoint and offset evidence';

INSERT INTO cdp_warehouse_stream_pipeline
(tenant_id, pipeline_key, display_name, source_type, source_ref, source_topic, consumer_group,
 processor_type, sink_type, sink_ref, delivery_semantics, checkpoint_interval_seconds,
 max_lag_ms, max_checkpoint_age_seconds, lifecycle_status, owner_name, config_json)
VALUES
(0, 'mysql_cdp_event_log_to_doris_ods', 'MySQL CDP Event Log To Doris ODS',
 'MYSQL_CDC', 'canvas.cdp_event_log', 'canvas.cdp_event_log', 'canvas-cdp-event-ods',
 'FLINK_CDC', 'DORIS', 'canvas_ods.cdp_event_log', 'EXACTLY_ONCE', 60, 300000, 300,
 'ACTIVE', 'data-platform',
 JSON_OBJECT('connector', 'flink-cdc', 'sink_connector', 'doris', 'schema_evolution', true)),
(0, 'mysql_canvas_trace_to_doris_ods', 'MySQL Canvas Trace To Doris ODS',
 'MYSQL_CDC', 'canvas.canvas_execution_trace', 'canvas.canvas_execution_trace', 'canvas-trace-ods',
 'FLINK_CDC', 'DORIS', 'canvas_ods.canvas_execution_trace', 'EXACTLY_ONCE', 60, 300000, 300,
 'ACTIVE', 'data-platform',
 JSON_OBJECT('connector', 'flink-cdc', 'sink_connector', 'doris', 'schema_evolution', true)),
(0, 'doris_ods_cdp_event_to_dwd_fact', 'Doris ODS CDP Event To DWD Fact',
 'DORIS', 'canvas_ods.cdp_event_log', NULL, 'canvas-cdp-dwd-fact',
 'FLINK_SQL', 'DORIS', 'canvas_dwd.cdp_user_event_fact', 'EXACTLY_ONCE', 60, 600000, 600,
 'ACTIVE', 'data-platform',
 JSON_OBJECT('watermark_column', 'event_time', 'sink_mode', 'insert_select')),
(0, 'doris_dwd_user_fact_to_dws_metric_daily', 'Doris DWD User Fact To DWS Metric Daily',
 'DORIS', 'canvas_dwd.cdp_user_event_fact', NULL, 'canvas-cdp-dws-daily',
 'FLINK_SQL', 'DORIS', 'canvas_dws.user_event_metric_daily', 'EXACTLY_ONCE', 120, 900000, 900,
 'ACTIVE', 'data-platform',
 JSON_OBJECT('watermark_column', 'event_date', 'sink_mode', 'aggregate_upsert'))
ON DUPLICATE KEY UPDATE
    display_name = VALUES(display_name),
    source_type = VALUES(source_type),
    source_ref = VALUES(source_ref),
    source_topic = VALUES(source_topic),
    consumer_group = VALUES(consumer_group),
    processor_type = VALUES(processor_type),
    sink_type = VALUES(sink_type),
    sink_ref = VALUES(sink_ref),
    delivery_semantics = VALUES(delivery_semantics),
    checkpoint_interval_seconds = VALUES(checkpoint_interval_seconds),
    max_lag_ms = VALUES(max_lag_ms),
    max_checkpoint_age_seconds = VALUES(max_checkpoint_age_seconds),
    lifecycle_status = VALUES(lifecycle_status),
    owner_name = VALUES(owner_name),
    config_json = VALUES(config_json),
    updated_at = CURRENT_TIMESTAMP;
