CREATE TABLE IF NOT EXISTS cdp_warehouse_external_realtime_job_probe_target (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    pipeline_key VARCHAR(128) NOT NULL,
    job_key VARCHAR(128) NOT NULL,
    engine_type VARCHAR(64) NOT NULL,
    endpoint_url VARCHAR(512) NOT NULL,
    auth_ref VARCHAR(128) DEFAULT NULL,
    external_job_id VARCHAR(128) DEFAULT NULL,
    connector_name VARCHAR(128) DEFAULT NULL,
    deployment_ref VARCHAR(256) DEFAULT NULL,
    enabled TINYINT(1) NOT NULL DEFAULT 1,
    owner_name VARCHAR(128) DEFAULT NULL,
    max_staleness_seconds INT NOT NULL DEFAULT 300,
    config_json JSON DEFAULT NULL,
    last_probed_at DATETIME DEFAULT NULL,
    last_probe_status VARCHAR(32) DEFAULT NULL,
    last_probe_message VARCHAR(1000) DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_cdp_warehouse_external_job_probe_target (tenant_id, pipeline_key, job_key),
    INDEX idx_cdp_warehouse_external_job_probe_enabled (tenant_id, enabled, engine_type),
    INDEX idx_cdp_warehouse_external_job_probe_status (tenant_id, last_probe_status, last_probed_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CDP warehouse external realtime job probe targets';
