CREATE TABLE IF NOT EXISTS cdp_warehouse_privacy_erasure_request (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    request_key VARCHAR(128) NOT NULL,
    subject_type VARCHAR(32) NOT NULL DEFAULT 'USER_ID',
    subject_hash VARCHAR(128) NOT NULL,
    subject_ref_masked VARCHAR(128) NOT NULL,
    reason VARCHAR(1000) NOT NULL,
    requested_by VARCHAR(128) NOT NULL DEFAULT 'system',
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    due_at DATETIME NOT NULL,
    started_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finished_at DATETIME DEFAULT NULL,
    target_assets_json JSON DEFAULT NULL,
    evidence_json JSON DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_cdp_warehouse_privacy_erasure_request (tenant_id, request_key),
    INDEX idx_cdp_warehouse_privacy_erasure_subject (tenant_id, subject_type, subject_hash),
    INDEX idx_cdp_warehouse_privacy_erasure_status_due (tenant_id, status, due_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CDP warehouse privacy erasure propagation requests';

CREATE TABLE IF NOT EXISTS cdp_warehouse_privacy_erasure_asset_proof (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    request_id BIGINT NOT NULL,
    request_key VARCHAR(128) NOT NULL,
    asset_key VARCHAR(128) NOT NULL,
    asset_layer VARCHAR(32) NOT NULL,
    action_type VARCHAR(64) NOT NULL DEFAULT 'ERASURE_PROOF',
    status VARCHAR(32) NOT NULL DEFAULT 'PLANNED',
    planned_action VARCHAR(1000) DEFAULT NULL,
    matched_count BIGINT NOT NULL DEFAULT 0,
    affected_count BIGINT NOT NULL DEFAULT 0,
    proof_message VARCHAR(1000) DEFAULT NULL,
    error_message VARCHAR(1000) DEFAULT NULL,
    executed_by VARCHAR(128) DEFAULT NULL,
    executed_at DATETIME DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_cdp_warehouse_privacy_erasure_asset (request_id, asset_key),
    INDEX idx_cdp_warehouse_privacy_erasure_asset_status (tenant_id, asset_key, status),
    INDEX idx_cdp_warehouse_privacy_erasure_asset_request (tenant_id, request_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CDP warehouse privacy erasure per-asset proof';
