CREATE TABLE IF NOT EXISTS conversation_private_contact (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT 'Tenant id',
    provider VARCHAR(64) NOT NULL COMMENT 'Private-domain provider such as WECOM',
    external_contact_id VARCHAR(128) NOT NULL COMMENT 'Provider external contact id',
    user_id VARCHAR(192) NOT NULL COMMENT 'Stable conversation user id, provider:external_contact_id',
    display_name VARCHAR(128) NULL COMMENT 'Contact display name',
    avatar_url VARCHAR(512) NULL COMMENT 'Contact avatar URL',
    corp_name VARCHAR(255) NULL COMMENT 'External company name',
    gender VARCHAR(32) NULL COMMENT 'Provider-normalized gender',
    union_id_hash VARCHAR(128) NULL COMMENT 'Hashed union id or cross-channel id',
    tags_json JSON NULL COMMENT 'Contact tags',
    attributes_json JSON NULL COMMENT 'Normalized contact attributes',
    raw_payload_json JSON NULL COMMENT 'Provider raw payload for audit',
    synced_at DATETIME NOT NULL COMMENT 'Latest sync time',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_conversation_private_contact (tenant_id, provider, external_contact_id),
    INDEX idx_conversation_private_contact_user (tenant_id, user_id),
    INDEX idx_conversation_private_contact_name (tenant_id, provider, display_name),
    INDEX idx_conversation_private_contact_synced (tenant_id, provider, synced_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='SCRM private-domain contacts';

CREATE TABLE IF NOT EXISTS conversation_private_contact_owner (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT 'Tenant id',
    provider VARCHAR(64) NOT NULL COMMENT 'Private-domain provider such as WECOM',
    external_contact_id VARCHAR(128) NOT NULL COMMENT 'Provider external contact id',
    owner_user_id VARCHAR(128) NOT NULL COMMENT 'Follow user or relationship owner',
    remark VARCHAR(255) NULL COMMENT 'Owner-side remark',
    state VARCHAR(255) NULL COMMENT 'Provider state or campaign marker',
    add_way VARCHAR(64) NULL COMMENT 'Provider add-way code',
    tags_json JSON NULL COMMENT 'Owner relationship tags',
    attributes_json JSON NULL COMMENT 'Owner relationship attributes',
    raw_payload_json JSON NULL COMMENT 'Provider raw relationship payload',
    synced_at DATETIME NOT NULL COMMENT 'Latest sync time',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_conversation_private_contact_owner (tenant_id, provider, external_contact_id, owner_user_id),
    INDEX idx_conversation_private_contact_owner_user (tenant_id, provider, owner_user_id),
    INDEX idx_conversation_private_contact_owner_contact (tenant_id, provider, external_contact_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='SCRM private-domain contact owner relationships';

CREATE TABLE IF NOT EXISTS conversation_private_group (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT 'Tenant id',
    provider VARCHAR(64) NOT NULL COMMENT 'Private-domain provider such as WECOM',
    external_group_id VARCHAR(128) NOT NULL COMMENT 'Provider customer group id',
    name VARCHAR(255) NOT NULL COMMENT 'Customer group name',
    owner_user_id VARCHAR(128) NULL COMMENT 'Group owner user id',
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE' COMMENT 'ACTIVE/DISMISSED/UNKNOWN',
    member_count INT NOT NULL DEFAULT 0 COMMENT 'Provider reported member count',
    created_at_remote DATETIME NULL COMMENT 'Provider group creation time',
    raw_payload_json JSON NULL COMMENT 'Provider raw group payload',
    synced_at DATETIME NOT NULL COMMENT 'Latest sync time',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_conversation_private_group (tenant_id, provider, external_group_id),
    INDEX idx_conversation_private_group_owner (tenant_id, provider, owner_user_id),
    INDEX idx_conversation_private_group_status (tenant_id, provider, status, synced_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='SCRM private-domain customer groups';

CREATE TABLE IF NOT EXISTS conversation_private_group_member (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT 'Tenant id',
    provider VARCHAR(64) NOT NULL COMMENT 'Private-domain provider such as WECOM',
    external_group_id VARCHAR(128) NOT NULL COMMENT 'Provider customer group id',
    member_user_id VARCHAR(128) NOT NULL COMMENT 'Provider member user id',
    member_type VARCHAR(32) NOT NULL DEFAULT 'EXTERNAL' COMMENT 'EXTERNAL/STAFF/UNKNOWN',
    display_name VARCHAR(128) NULL COMMENT 'Member display name',
    union_id_hash VARCHAR(128) NULL COMMENT 'Hashed union id or cross-channel id',
    join_time DATETIME NULL COMMENT 'Provider join time',
    raw_payload_json JSON NULL COMMENT 'Provider raw member payload',
    synced_at DATETIME NOT NULL COMMENT 'Latest sync time',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_conversation_private_group_member (tenant_id, provider, external_group_id, member_user_id),
    INDEX idx_conversation_private_group_member_group (tenant_id, provider, external_group_id),
    INDEX idx_conversation_private_group_member_user (tenant_id, provider, member_user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='SCRM private-domain customer group members';

CREATE TABLE IF NOT EXISTS conversation_private_sync_run (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT 'Tenant id',
    provider VARCHAR(64) NOT NULL COMMENT 'Private-domain provider such as WECOM',
    sync_type VARCHAR(32) NOT NULL COMMENT 'CONTACTS/GROUPS/FULL',
    status VARCHAR(32) NOT NULL DEFAULT 'RUNNING' COMMENT 'RUNNING/SUCCESS/FAILED',
    requested_by VARCHAR(128) NOT NULL DEFAULT 'system' COMMENT 'Operator or sync worker',
    source_cursor VARCHAR(512) NULL COMMENT 'Provider source cursor',
    next_cursor VARCHAR(512) NULL COMMENT 'Provider next cursor',
    contact_count INT NOT NULL DEFAULT 0 COMMENT 'Contacts received',
    contact_upserted INT NOT NULL DEFAULT 0 COMMENT 'Contacts upserted',
    group_count INT NOT NULL DEFAULT 0 COMMENT 'Groups received',
    group_upserted INT NOT NULL DEFAULT 0 COMMENT 'Groups upserted',
    member_count INT NOT NULL DEFAULT 0 COMMENT 'Members received',
    member_upserted INT NOT NULL DEFAULT 0 COMMENT 'Members upserted',
    failed_count INT NOT NULL DEFAULT 0 COMMENT 'Failed records',
    error_message VARCHAR(1024) NULL COMMENT 'Failure message',
    metadata_json JSON NULL COMMENT 'Sync metadata',
    started_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_conversation_private_sync_run_provider (tenant_id, provider, sync_type, created_at),
    INDEX idx_conversation_private_sync_run_status (tenant_id, status, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='SCRM private-domain sync runs';
