CREATE TABLE IF NOT EXISTS `creator_profile` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `tenant_id` BIGINT NOT NULL,
  `provider` VARCHAR(64) NOT NULL,
  `handle` VARCHAR(255) NOT NULL,
  `handle_key` VARCHAR(255) NOT NULL,
  `display_name` VARCHAR(255) NULL,
  `creator_tier` VARCHAR(64) NULL,
  `primary_channel` VARCHAR(64) NULL,
  `follower_count` BIGINT NOT NULL DEFAULT 0,
  `avg_engagement_rate` DECIMAL(9,6) NOT NULL DEFAULT 0.000000,
  `tags_json` JSON NULL,
  `status` VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
  `risk_status` VARCHAR(32) NOT NULL DEFAULT 'NORMAL',
  `metadata_json` JSON NULL,
  `created_by` VARCHAR(128) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `uk_creator_profile_identity` (`tenant_id`, `provider`, `handle_key`),
  KEY `idx_creator_profile_status` (`tenant_id`, `status`, `risk_status`),
  KEY `idx_creator_profile_channel` (`tenant_id`, `primary_channel`, `creator_tier`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Creator and KOL/KOC normalized profiles';

CREATE TABLE IF NOT EXISTS `creator_campaign` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `tenant_id` BIGINT NOT NULL,
  `campaign_key` VARCHAR(128) NOT NULL,
  `campaign_name` VARCHAR(255) NOT NULL,
  `objective` VARCHAR(64) NULL,
  `budget_amount` DECIMAL(18,4) NOT NULL DEFAULT 0.0000,
  `currency` VARCHAR(16) NOT NULL DEFAULT 'CNY',
  `start_at` DATETIME NULL,
  `end_at` DATETIME NULL,
  `status` VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
  `metadata_json` JSON NULL,
  `created_by` VARCHAR(128) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `uk_creator_campaign_key` (`tenant_id`, `campaign_key`),
  KEY `idx_creator_campaign_status` (`tenant_id`, `status`, `start_at`, `end_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Creator collaboration campaign briefs';

CREATE TABLE IF NOT EXISTS `creator_collaboration` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `tenant_id` BIGINT NOT NULL,
  `campaign_id` BIGINT NOT NULL,
  `creator_id` BIGINT NOT NULL,
  `offer_type` VARCHAR(64) NULL,
  `fixed_fee_amount` DECIMAL(18,4) NOT NULL DEFAULT 0.0000,
  `commission_rate` DECIMAL(9,6) NOT NULL DEFAULT 0.000000,
  `tracking_link` VARCHAR(512) NULL,
  `discount_code` VARCHAR(128) NULL,
  `status` VARCHAR(32) NOT NULL DEFAULT 'NEGOTIATING',
  `permissions_metadata_json` JSON NULL,
  `metadata_json` JSON NULL,
  `created_by` VARCHAR(128) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `uk_creator_collaboration_creator_campaign` (`tenant_id`, `campaign_id`, `creator_id`),
  KEY `idx_creator_collaboration_creator` (`tenant_id`, `creator_id`, `status`),
  KEY `idx_creator_collaboration_campaign` (`tenant_id`, `campaign_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Creator campaign collaboration contracts and tracking setup';

CREATE TABLE IF NOT EXISTS `creator_deliverable` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `tenant_id` BIGINT NOT NULL,
  `collaboration_id` BIGINT NOT NULL,
  `campaign_id` BIGINT NOT NULL,
  `creator_id` BIGINT NOT NULL,
  `deliverable_key` VARCHAR(128) NOT NULL,
  `content_type` VARCHAR(64) NOT NULL,
  `platform` VARCHAR(64) NULL,
  `due_at` DATETIME NULL,
  `posted_at` DATETIME NULL,
  `content_url` VARCHAR(512) NULL,
  `status` VARCHAR(32) NOT NULL DEFAULT 'PLANNED',
  `impression_count` BIGINT NOT NULL DEFAULT 0,
  `like_count` BIGINT NOT NULL DEFAULT 0,
  `comment_count` BIGINT NOT NULL DEFAULT 0,
  `share_count` BIGINT NOT NULL DEFAULT 0,
  `save_count` BIGINT NOT NULL DEFAULT 0,
  `click_count` BIGINT NOT NULL DEFAULT 0,
  `conversion_count` BIGINT NOT NULL DEFAULT 0,
  `revenue_amount` DECIMAL(18,4) NOT NULL DEFAULT 0.0000,
  `metadata_json` JSON NULL,
  `created_by` VARCHAR(128) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `uk_creator_deliverable_key` (`tenant_id`, `collaboration_id`, `deliverable_key`),
  KEY `idx_creator_deliverable_due` (`tenant_id`, `due_at`, `status`),
  KEY `idx_creator_deliverable_campaign` (`tenant_id`, `campaign_id`, `status`),
  KEY `idx_creator_deliverable_creator` (`tenant_id`, `creator_id`, `posted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Creator collaboration deliverables and performance evidence';
