CREATE TABLE IF NOT EXISTS `search_marketing_source` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `tenant_id` BIGINT NOT NULL,
  `provider` VARCHAR(64) NOT NULL,
  `source_key` VARCHAR(128) NOT NULL,
  `display_name` VARCHAR(255) NOT NULL,
  `channel` VARCHAR(16) NOT NULL,
  `external_account_id` VARCHAR(128) NULL,
  `site_url` VARCHAR(512) NULL,
  `currency` VARCHAR(16) NOT NULL DEFAULT 'CNY',
  `timezone` VARCHAR(64) NOT NULL DEFAULT 'UTC',
  `enabled` TINYINT NOT NULL DEFAULT 1,
  `metadata_json` JSON NULL,
  `created_by` VARCHAR(128) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `uk_search_marketing_source_identity` (`tenant_id`, `provider`, `source_key`),
  KEY `idx_search_marketing_source_channel` (`tenant_id`, `channel`, `enabled`),
  KEY `idx_search_marketing_source_updated` (`tenant_id`, `updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='SEO and SEM search marketing source registry';

CREATE TABLE IF NOT EXISTS `search_marketing_keyword` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `tenant_id` BIGINT NOT NULL,
  `channel` VARCHAR(16) NOT NULL,
  `keyword_text` VARCHAR(512) NOT NULL,
  `keyword_key` VARCHAR(512) NOT NULL,
  `match_type` VARCHAR(32) NOT NULL DEFAULT 'EXACT',
  `landing_page_url` VARCHAR(512) NULL,
  `landing_page_url_hash` VARCHAR(128) NOT NULL,
  `search_intent` VARCHAR(64) NULL,
  `labels_json` JSON NULL,
  `status` VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
  `metadata_json` JSON NULL,
  `created_by` VARCHAR(128) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `uk_search_marketing_keyword_identity` (`tenant_id`, `channel`, `keyword_key`, `match_type`, `landing_page_url_hash`),
  KEY `idx_search_marketing_keyword_status` (`tenant_id`, `channel`, `status`),
  KEY `idx_search_marketing_keyword_intent` (`tenant_id`, `search_intent`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='SEO and SEM keyword portfolio';

CREATE TABLE IF NOT EXISTS `search_marketing_snapshot` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `tenant_id` BIGINT NOT NULL,
  `source_id` BIGINT NOT NULL,
  `keyword_id` BIGINT NOT NULL,
  `channel` VARCHAR(16) NOT NULL,
  `snapshot_date` DATE NOT NULL,
  `device` VARCHAR(32) NOT NULL DEFAULT 'ALL',
  `country` VARCHAR(32) NOT NULL DEFAULT 'ALL',
  `query_group_key` VARCHAR(128) NOT NULL DEFAULT 'DEFAULT',
  `impression_count` BIGINT NOT NULL DEFAULT 0,
  `click_count` BIGINT NOT NULL DEFAULT 0,
  `cost_amount` DECIMAL(18,4) NOT NULL DEFAULT 0.0000,
  `conversion_count` BIGINT NOT NULL DEFAULT 0,
  `revenue_amount` DECIMAL(18,4) NOT NULL DEFAULT 0.0000,
  `average_position` DECIMAL(10,4) NULL,
  `metadata_json` JSON NULL,
  `created_by` VARCHAR(128) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `uk_search_marketing_snapshot_daily` (`tenant_id`, `source_id`, `keyword_id`, `snapshot_date`, `device`, `country`, `query_group_key`),
  KEY `idx_search_marketing_snapshot_scope` (`tenant_id`, `channel`, `snapshot_date`),
  KEY `idx_search_marketing_snapshot_source` (`tenant_id`, `source_id`, `snapshot_date`),
  KEY `idx_search_marketing_snapshot_keyword` (`tenant_id`, `keyword_id`, `snapshot_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='SEO and SEM daily keyword performance snapshots';

CREATE TABLE IF NOT EXISTS `search_marketing_opportunity` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `tenant_id` BIGINT NOT NULL,
  `source_id` BIGINT NOT NULL,
  `keyword_id` BIGINT NOT NULL,
  `channel` VARCHAR(16) NOT NULL,
  `opportunity_type` VARCHAR(64) NOT NULL,
  `snapshot_date` DATE NOT NULL,
  `severity` VARCHAR(32) NOT NULL DEFAULT 'MEDIUM',
  `status` VARCHAR(32) NOT NULL DEFAULT 'OPEN',
  `recommendation` VARCHAR(1000) NOT NULL,
  `impact_score` DECIMAL(10,4) NOT NULL DEFAULT 0.0000,
  `evidence_json` JSON NULL,
  `created_by` VARCHAR(128) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `uk_search_marketing_opportunity_identity` (`tenant_id`, `source_id`, `keyword_id`, `opportunity_type`, `snapshot_date`),
  KEY `idx_search_marketing_opportunity_status` (`tenant_id`, `status`, `severity`, `created_at`),
  KEY `idx_search_marketing_opportunity_keyword` (`tenant_id`, `keyword_id`, `created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='SEO and SEM deterministic optimization opportunities';
