CREATE TABLE IF NOT EXISTS marketing_monitor_inference (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  tenant_id BIGINT NOT NULL DEFAULT 0,
  item_id BIGINT NOT NULL,
  source_id BIGINT NULL,
  provider_id BIGINT NULL,
  template_id BIGINT NULL,
  model_key VARCHAR(128) NOT NULL,
  model_version VARCHAR(128) NOT NULL,
  provider_status VARCHAR(64) NOT NULL,
  fallback_used TINYINT(1) NOT NULL DEFAULT 0,
  input_hash VARCHAR(64) NOT NULL,
  prompt_hash VARCHAR(64) NOT NULL,
  sentiment_label VARCHAR(32) NOT NULL,
  sentiment_score DECIMAL(8,5) NOT NULL DEFAULT 0.00000,
  confidence DECIMAL(6,5) NOT NULL DEFAULT 0.00000,
  entities_json JSON NULL,
  topics_json JSON NULL,
  risk_flags_json JSON NULL,
  evidence_json JSON NULL,
  latency_ms BIGINT NOT NULL DEFAULT 0,
  requested_by VARCHAR(128) NOT NULL DEFAULT 'system',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_monitor_inference_item (tenant_id, item_id, created_at),
  KEY idx_monitor_inference_status (tenant_id, provider_status, fallback_used, created_at),
  KEY idx_monitor_inference_model (tenant_id, model_key, model_version, created_at),
  KEY idx_monitor_inference_hash (tenant_id, input_hash, prompt_hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Governed LLM sentiment inference ledger for marketing monitoring items';
