CREATE TABLE IF NOT EXISTS marketing_monitor_provider_credential (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  tenant_id BIGINT NOT NULL DEFAULT 0,
  credential_key VARCHAR(128) NOT NULL,
  provider_type VARCHAR(64) NOT NULL,
  auth_type VARCHAR(64) NOT NULL,
  display_name VARCHAR(128) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
  token_type VARCHAR(64) NULL,
  scopes_json JSON NULL,
  access_token_prefix VARCHAR(16) NULL,
  access_token_hash VARCHAR(120) NULL,
  access_token_ciphertext VARCHAR(2000) NULL,
  refresh_token_prefix VARCHAR(16) NULL,
  refresh_token_hash VARCHAR(120) NULL,
  refresh_token_ciphertext VARCHAR(2000) NULL,
  api_key_prefix VARCHAR(16) NULL,
  api_key_hash VARCHAR(120) NULL,
  api_key_ciphertext VARCHAR(2000) NULL,
  client_id_ciphertext VARCHAR(1000) NULL,
  client_secret_ciphertext VARCHAR(2000) NULL,
  refresh_endpoint VARCHAR(512) NULL,
  expires_at DATETIME NULL,
  refresh_token_expires_at DATETIME NULL,
  last_refreshed_at DATETIME NULL,
  refresh_attempt_count INT NOT NULL DEFAULT 0,
  last_refresh_status VARCHAR(64) NULL,
  last_refresh_error VARCHAR(1000) NULL,
  metadata_json JSON NULL,
  created_by VARCHAR(128) NOT NULL DEFAULT 'system',
  updated_by VARCHAR(128) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_monitor_provider_credential (tenant_id, credential_key),
  KEY idx_monitor_provider_credential_status (tenant_id, provider_type, auth_type, status),
  KEY idx_monitor_provider_credential_expiry (tenant_id, status, expires_at),
  KEY idx_monitor_provider_credential_updated (tenant_id, updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Encrypted provider credentials for marketing monitoring connectors';

CREATE TABLE IF NOT EXISTS marketing_monitor_provider_credential_event (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  tenant_id BIGINT NOT NULL DEFAULT 0,
  credential_id BIGINT NOT NULL,
  credential_key VARCHAR(128) NOT NULL,
  event_type VARCHAR(64) NOT NULL,
  status VARCHAR(64) NOT NULL,
  metadata_json JSON NULL,
  error_message VARCHAR(1000) NULL,
  created_by VARCHAR(128) NOT NULL DEFAULT 'system',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_monitor_provider_credential_event (tenant_id, credential_id, created_at),
  KEY idx_monitor_provider_credential_event_type (tenant_id, event_type, status, created_at),
  KEY idx_monitor_provider_credential_event_key (tenant_id, credential_key, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Lifecycle events for marketing monitoring provider credentials';
