CREATE TABLE IF NOT EXISTS `programmatic_dsp_mutation` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `tenant_id` BIGINT NOT NULL,
  `seat_id` BIGINT NOT NULL,
  `campaign_id` BIGINT NULL,
  `line_item_id` BIGINT NULL,
  `supply_path_id` BIGINT NULL,
  `provider` VARCHAR(64) NOT NULL,
  `mutation_key` VARCHAR(128) NOT NULL,
  `mutation_type` VARCHAR(64) NOT NULL,
  `entity_type` VARCHAR(64) NOT NULL,
  `external_entity_id` VARCHAR(255) NULL,
  `request_hash` CHAR(64) NOT NULL,
  `idempotency_key` VARCHAR(128) NOT NULL,
  `status` VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
  `approval_status` VARCHAR(32) NOT NULL DEFAULT 'PENDING',
  `dry_run_required` TINYINT NOT NULL DEFAULT 1,
  `payload_json` JSON NOT NULL,
  `validation_json` JSON NULL,
  `provider_request_json` JSON NULL,
  `provider_response_json` JSON NULL,
  `error_code` VARCHAR(128) NULL,
  `error_message` VARCHAR(1000) NULL,
  `created_by` VARCHAR(128) NULL,
  `approved_by` VARCHAR(128) NULL,
  `approved_at` DATETIME NULL,
  `executed_by` VARCHAR(128) NULL,
  `executed_at` DATETIME NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_programmatic_dsp_mutation_key` (`tenant_id`, `mutation_key`),
  UNIQUE KEY `uk_programmatic_dsp_mutation_idempotency` (`tenant_id`, `seat_id`, `idempotency_key`),
  KEY `idx_programmatic_dsp_mutation_status` (`tenant_id`, `status`, `approval_status`, `updated_at`),
  KEY `idx_programmatic_dsp_mutation_seat` (`tenant_id`, `seat_id`, `updated_at`),
  KEY `idx_programmatic_dsp_mutation_campaign` (`tenant_id`, `campaign_id`, `updated_at`),
  KEY `idx_programmatic_dsp_mutation_line_item` (`tenant_id`, `line_item_id`, `updated_at`),
  KEY `idx_programmatic_dsp_mutation_supply_path` (`tenant_id`, `supply_path_id`, `updated_at`)
);
