CREATE TABLE IF NOT EXISTS `search_marketing_sync_run` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `tenant_id` BIGINT NOT NULL,
  `source_id` BIGINT NOT NULL,
  `run_type` VARCHAR(40) NOT NULL,
  `provider` VARCHAR(64) NOT NULL,
  `channel` VARCHAR(16) NOT NULL,
  `idempotency_key` VARCHAR(128) NOT NULL,
  `window_start` DATE NULL,
  `window_end` DATE NULL,
  `cursor_value` VARCHAR(512) NULL,
  `status` VARCHAR(32) NOT NULL DEFAULT 'RUNNING',
  `retryable` TINYINT NOT NULL DEFAULT 0,
  `requested_count` BIGINT NOT NULL DEFAULT 0,
  `success_count` BIGINT NOT NULL DEFAULT 0,
  `failed_count` BIGINT NOT NULL DEFAULT 0,
  `provider_request_id` VARCHAR(128) NULL,
  `error_code` VARCHAR(128) NULL,
  `error_message` VARCHAR(1000) NULL,
  `evidence_json` JSON NULL,
  `created_by` VARCHAR(128) NULL,
  `started_at` DATETIME NOT NULL,
  `finished_at` DATETIME NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_search_marketing_sync_run_idempotency` (`tenant_id`, `source_id`, `run_type`, `idempotency_key`),
  KEY `idx_search_marketing_sync_run_status` (`tenant_id`, `status`, `run_type`, `started_at`),
  KEY `idx_search_marketing_sync_run_source` (`tenant_id`, `source_id`, `status`, `updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Search marketing provider sync run ledger';

CREATE TABLE IF NOT EXISTS `search_marketing_url_inspection` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `tenant_id` BIGINT NOT NULL,
  `source_id` BIGINT NOT NULL,
  `provider` VARCHAR(64) NOT NULL,
  `page_url` VARCHAR(1000) NOT NULL,
  `page_url_hash` CHAR(64) NOT NULL,
  `inspection_date` DATE NOT NULL,
  `indexed_state` VARCHAR(64) NOT NULL DEFAULT 'UNKNOWN',
  `crawl_state` VARCHAR(64) NOT NULL DEFAULT 'UNKNOWN',
  `canonical_url` VARCHAR(1000) NULL,
  `sitemap_state` VARCHAR(64) NOT NULL DEFAULT 'UNKNOWN',
  `mobile_usability_state` VARCHAR(64) NOT NULL DEFAULT 'UNKNOWN',
  `last_crawl_at` DATETIME NULL,
  `evidence_json` JSON NULL,
  `created_by` VARCHAR(128) NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_search_marketing_url_inspection_daily` (`tenant_id`, `source_id`, `page_url_hash`, `inspection_date`, `provider`),
  KEY `idx_search_marketing_url_inspection_state` (`tenant_id`, `indexed_state`, `crawl_state`, `inspection_date`),
  KEY `idx_search_marketing_url_inspection_source` (`tenant_id`, `source_id`, `inspection_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='SEO URL inspection and index evidence';

CREATE TABLE IF NOT EXISTS `search_marketing_provider_change` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `tenant_id` BIGINT NOT NULL,
  `source_id` BIGINT NOT NULL,
  `mutation_id` BIGINT NULL,
  `provider` VARCHAR(64) NOT NULL,
  `external_resource_id` VARCHAR(255) NOT NULL,
  `change_type` VARCHAR(64) NOT NULL,
  `changed_fields_json` JSON NULL,
  `provider_actor` VARCHAR(255) NULL,
  `provider_changed_at` DATETIME NOT NULL,
  `reconciliation_status` VARCHAR(32) NOT NULL DEFAULT 'PENDING',
  `evidence_json` JSON NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_search_marketing_provider_change` (`tenant_id`, `source_id`, `provider`, `external_resource_id`, `provider_changed_at`),
  KEY `idx_search_marketing_provider_change_reconcile` (`tenant_id`, `reconciliation_status`, `provider_changed_at`),
  KEY `idx_search_marketing_provider_change_mutation` (`tenant_id`, `mutation_id`, `updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Search provider change-history reconciliation evidence';

CREATE TABLE IF NOT EXISTS `search_marketing_impact_window` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `tenant_id` BIGINT NOT NULL,
  `opportunity_id` BIGINT NOT NULL,
  `mutation_id` BIGINT NULL,
  `source_id` BIGINT NOT NULL,
  `keyword_id` BIGINT NULL,
  `page_url_hash` CHAR(64) NULL,
  `baseline_start_date` DATE NOT NULL,
  `baseline_end_date` DATE NOT NULL,
  `post_start_date` DATE NOT NULL,
  `post_end_date` DATE NOT NULL,
  `status` VARCHAR(32) NOT NULL DEFAULT 'PENDING',
  `decision` VARCHAR(64) NULL,
  `confidence` DECIMAL(8,4) NULL,
  `metric_delta_json` JSON NULL,
  `evidence_json` JSON NULL,
  `due_at` DATETIME NOT NULL,
  `evaluated_at` DATETIME NULL,
  `created_by` VARCHAR(128) NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_search_marketing_impact_window` (`tenant_id`, `opportunity_id`, `mutation_id`, `baseline_start_date`, `post_start_date`),
  KEY `idx_search_marketing_impact_window_due` (`tenant_id`, `status`, `due_at`),
  KEY `idx_search_marketing_impact_window_source` (`tenant_id`, `source_id`, `post_end_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Search marketing post-change impact proof windows';
