CREATE TABLE IF NOT EXISTS `marketing_integration_contract` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `tenant_id` BIGINT NOT NULL,
  `contract_key` VARCHAR(128) NOT NULL,
  `display_name` VARCHAR(255) NOT NULL,
  `provider_family` VARCHAR(64) NOT NULL,
  `source_capability_key` VARCHAR(128) NOT NULL,
  `target_capability_key` VARCHAR(128) NOT NULL,
  `asset_key` VARCHAR(128) NOT NULL,
  `direction` VARCHAR(32) NOT NULL DEFAULT 'OUTBOUND',
  `environment` VARCHAR(32) NOT NULL DEFAULT 'PRODUCTION',
  `auth_mode` VARCHAR(32) NOT NULL DEFAULT 'OAUTH',
  `credential_dependency` VARCHAR(255) NULL,
  `api_root` VARCHAR(512) NOT NULL,
  `owner_team` VARCHAR(128) NULL,
  `status` VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
  `sla_tier` VARCHAR(32) NOT NULL DEFAULT 'STANDARD',
  `timeout_ms` INT NOT NULL DEFAULT 30000,
  `retry_policy_json` JSON NULL,
  `schema_contract_json` JSON NULL,
  `metadata_json` JSON NULL,
  `created_by` VARCHAR(128) NULL,
  `updated_by` VARCHAR(128) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_marketing_integration_contract_key` (`tenant_id`, `contract_key`),
  KEY `idx_marketing_integration_contract_status` (`tenant_id`, `environment`, `status`, `updated_at`),
  KEY `idx_marketing_integration_contract_provider` (`tenant_id`, `provider_family`, `status`),
  KEY `idx_marketing_integration_contract_asset` (`tenant_id`, `asset_key`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Tenant-scoped marketing API integration contract registry for middle-platform glue governance';
