ALTER TABLE notification
    ADD COLUMN category VARCHAR(32) NOT NULL DEFAULT 'TASK' AFTER type,
    ADD COLUMN severity VARCHAR(16) NOT NULL DEFAULT 'INFO' AFTER category,
    ADD COLUMN status VARCHAR(16) NOT NULL DEFAULT 'UNREAD' AFTER severity,
    ADD COLUMN biz_type VARCHAR(64) NULL AFTER task_id,
    ADD COLUMN biz_id VARCHAR(128) NULL AFTER biz_type,
    ADD COLUMN action_label VARCHAR(64) NULL AFTER target_url,
    ADD COLUMN action_url VARCHAR(500) NULL AFTER action_label,
    ADD COLUMN dedup_key VARCHAR(200) NULL AFTER biz_id,
    ADD COLUMN payload_json JSON NULL AFTER dedup_key,
    ADD COLUMN archived_at DATETIME NULL AFTER read_at,
    ADD COLUMN delivered_at DATETIME NULL AFTER archived_at,
    ADD UNIQUE KEY uk_notification_user_dedup (user_id, dedup_key),
    ADD INDEX idx_notification_user_category (user_id, category, created_at),
    ADD INDEX idx_notification_user_archived (user_id, archived_at, created_at),
    ADD INDEX idx_notification_severity (severity, created_at);
