INSERT INTO node_type_registry
  (type_key, type_name, category, handler_class,
   config_schema, output_schema, outlet_schema, summary_template, runtime_policy_schema,
   risk_level, is_trigger, is_terminal, description, enabled)
VALUES
('API_TRIGGER','API 触发','入口节点','org.chovy.canvas.engine.handlers.ApiTriggerHandler',
 '[{"key":"acceptedProperties","label":"接收参数","type":"key-value"}]',
 '[{"name":"apiTriggered","type":"BOOLEAN","label":"API已触发"}]',
 '[{"id":"success","label":"继续","color":"#52c41a","targetField":"nextNodeId"}]',
 'API 触发','[]','MEDIUM',1,0,'外部系统通过 API 将用户推入旅程。',1),
('AUDIENCE_TRIGGER','受众触发','入口节点','org.chovy.canvas.engine.handlers.AudienceTriggerHandler',
 '[{"key":"segmentId","label":"受众ID","type":"text","required":true},{"key":"triggerOn","label":"触发时机","type":"select","defaultValue":"ENTER","options":[{"label":"进入","value":"ENTER"},{"label":"离开","value":"EXIT"}]}]',
 '[{"name":"audienceMatched","type":"BOOLEAN","label":"受众是否匹配"}]',
 '[{"id":"success","label":"继续","color":"#52c41a","targetField":"nextNodeId"}]',
 '受众触发（{{segmentId}}）','[]','MEDIUM',1,0,'用户进入或离开指定受众时触发旅程。',1),
('UPDATE_PROFILE','更新属性','数据操作','org.chovy.canvas.engine.handlers.UpdateProfileHandler',
 '[{"key":"operations","label":"更新操作","type":"json","required":true}]',
 '[{"name":"profileUpdated","type":"BOOLEAN","label":"画像已更新"}]',
 '[{"id":"success","label":"成功","color":"#52c41a","targetField":"nextNodeId"}]',
 '更新属性','[]','MEDIUM',0,0,'更新用户画像字段和扩展属性。',1),
('TAG_OPERATION','标签操作','数据操作','org.chovy.canvas.engine.handlers.TagOperationHandler',
 '[{"key":"operations","label":"标签操作","type":"json","required":true}]',
 '[{"name":"tagsChanged","type":"NUMBER","label":"变更标签数"}]',
 '[{"id":"success","label":"成功","color":"#52c41a","targetField":"nextNodeId"}]',
 '标签操作','[]','MEDIUM',0,0,'添加或移除用户标签，支持临时标签过期时间。',1),
('POINTS_OPERATION','积分操作','权益发放','org.chovy.canvas.engine.handlers.PointsOperationHandler',
 '[{"key":"operation","label":"操作","type":"select","defaultValue":"GRANT","options":[{"label":"发放","value":"GRANT"},{"label":"扣减","value":"DEDUCT"}]},{"key":"points","label":"积分","type":"number","required":true},{"key":"pointsType","label":"积分类型","type":"text","defaultValue":"MARKETING"},{"key":"idempotencyKey","label":"幂等键","type":"text"}]',
 '[{"name":"pointsLedgerId","type":"NUMBER","label":"积分流水ID"},{"name":"duplicate","type":"BOOLEAN","label":"是否重复"}]',
 '[{"id":"success","label":"成功","color":"#52c41a","targetField":"nextNodeId"}]',
 '积分操作（{{points}}）','[]','HIGH',0,0,'写入积分发放或扣减流水，并用幂等键防重复。',1),
('CREATE_TASK','创建任务','内部动作','org.chovy.canvas.engine.handlers.CreateTaskHandler',
 '[{"key":"taskType","label":"任务类型","type":"text","defaultValue":"FOLLOW_UP"},{"key":"title","label":"标题","type":"text","required":true},{"key":"description","label":"描述","type":"multi-text"},{"key":"priority","label":"优先级","type":"select","defaultValue":"NORMAL","options":[{"label":"普通","value":"NORMAL"},{"label":"高","value":"HIGH"}]},{"key":"assignee","label":"负责人","type":"text"},{"key":"dueHours","label":"截止小时","type":"number"}]',
 '[{"name":"taskId","type":"NUMBER","label":"任务ID"}]',
 '[{"id":"success","label":"成功","color":"#52c41a","targetField":"nextNodeId"}]',
 '创建任务（{{title}}）','[]','MEDIUM',0,0,'创建人工跟进任务记录。',1),
('TRACK_EVENT','记录事件','内部动作','org.chovy.canvas.engine.handlers.TrackEventHandler',
 '[{"key":"eventCode","label":"事件编码","type":"text","required":true},{"key":"attributes","label":"事件属性","type":"key-value"}]',
 '[{"name":"eventLogId","type":"NUMBER","label":"事件日志ID"}]',
 '[{"id":"success","label":"成功","color":"#52c41a","targetField":"nextNodeId"}]',
 '记录事件（{{eventCode}}）','[]','LOW',0,0,'向事件日志写入一条旅程内部事件。',1);
