-- V90 governed final node catalog consolidation

DELETE FROM node_type_registry WHERE type_key NOT IN ('START','END','DIRECT_RETURN','DIRECT_CALL','EVENT_TRIGGER','MQ_TRIGGER','SCHEDULED_TRIGGER','IF_CONDITION','SPLIT','WAIT','HUB','AGGREGATE','THRESHOLD','API_CALL','SEND_MQ','GROOVY','SEND_MESSAGE','TAGGER','COMMIT_ACTION','SUB_FLOW_REF');

INSERT INTO node_type_registry
  (type_key, type_name, category, handler_class, config_schema, output_schema, outlet_schema, summary_template, runtime_policy_schema, risk_level, is_trigger, is_terminal, description, enabled)
VALUES
('START','开始','基础控制','org.chovy.canvas.engine.handlers.StartHandler','[]','[]','[{"id":"success","label":"继续","color":"#52c41a","targetField":"nextNodeId"}]','开始','[]','LOW',0,0,'画布流程起点。',1),
('END','结束','基础控制','org.chovy.canvas.engine.handlers.EndHandler','[]','[]','[]','结束','[]','LOW',0,1,'画布流程终点。',1),
('DIRECT_RETURN','直调返回','基础控制','org.chovy.canvas.engine.handlers.DirectReturnHandler','[{"key":"buildType","label":"构建方式","type":"radio","defaultValue":"CUSTOM","options":[{"label":"自定义","value":"CUSTOM"}]},{"key":"data","label":"返回数据","type":"context-value-list"}]','[]','[]','直调返回','[]','LOW',0,1,'配合直调入口同步返回结果。',1),
('DIRECT_CALL','API入口','入口触发','org.chovy.canvas.engine.handlers.DirectCallHandler','[]','[]','[]','API入口','[]','MEDIUM',1,0,'外部系统通过直调接口触发画布；下游分支由画布连线自动生成。',1),
('EVENT_TRIGGER','事件触发','入口触发','org.chovy.canvas.engine.handlers.EventTriggerHandler','[{"key":"eventCode","label":"事件","type":"select","dataSource":"/meta/event-definitions","required":true},{"key":"eventAttrs","label":"事件属性","type":"event-attr-preview","dataSource":"/meta/event-definitions/{eventCode}/attrs"}]','[{"fieldKey":"eventCode","fieldName":"事件编码","dataType":"STRING"},{"fieldKey":"userId","fieldName":"用户ID","dataType":"STRING"}]','[{"id":"success","label":"继续","color":"#52c41a","targetField":"nextNodeId"}]','事件触发（{{eventCode}}）','[]','LOW',1,0,'业务事件上报后触发画布。',1),
('MQ_TRIGGER','MQ消息触发','入口触发','org.chovy.canvas.engine.handlers.MqTriggerHandler','[{"key":"topicKey","label":"消息主题","type":"select","dataSource":"/meta/mq-topics","required":true},{"key":"validateResult","label":"开启消息校验","type":"toggle"},{"key":"validateRules","label":"校验规则","type":"condition-rule-list","visible":"validateResult==true"}]','[{"fieldKey":"orderId","fieldName":"订单号","dataType":"STRING"},{"fieldKey":"userId","fieldName":"用户ID","dataType":"STRING"}]','[{"id":"success","label":"继续","color":"#52c41a","targetField":"nextNodeId"}]','MQ消息（{{topicKey}}）','[]','LOW',1,0,'消费业务 MQ 消息后触发画布。',1),
('SCHEDULED_TRIGGER','定时触发','入口触发','org.chovy.canvas.engine.handlers.ScheduledTriggerHandler','[{"key":"scheduleType","label":"触发类型","type":"radio","required":true,"options":[{"label":"指定时间(ONCE)","value":"ONCE"},{"label":"周期(CRON)","value":"CRON"}]},{"key":"cronExpression","label":"Cron 表达式","type":"cron","visible":"scheduleType==CRON","required":true},{"key":"triggerTime","label":"触发时间","type":"datetime","visible":"scheduleType==ONCE","required":true},{"key":"timezone","label":"时区","type":"input","defaultValue":"Asia/Shanghai"}]','[]','[{"id":"success","label":"继续","color":"#52c41a","targetField":"nextNodeId"}]','定时触发','[]','LOW',1,0,'按固定时间或周期触发画布。',1),
('IF_CONDITION','IF判断','条件与分流','org.chovy.canvas.engine.handlers.IfConditionHandler','[{"key":"rules","label":"条件规则","type":"condition-rule-list","required":true}]','[]','[{"id":"success","label":"条件成立","color":"#52c41a","targetField":"successNodeId"},{"id":"fail","label":"否则","color":"#8c8c8c","targetField":"failNodeId"}]','IF判断','[]','LOW',0,0,'按规则判断后选择成功或失败路径。',1),
('SPLIT','通用分流','条件与分流','org.chovy.canvas.engine.handlers.SplitHandler','[{"key":"splitKey","label":"分流键","type":"text","defaultValue":"default"},{"key":"allocationStrategy","label":"分配策略","type":"select","defaultValue":"CONSISTENT","options":[{"label":"稳定分配","value":"CONSISTENT"},{"label":"随机分配","value":"RANDOM"}]},{"key":"branches","label":"分支","type":"split-branch-list","required":true}]','[{"fieldKey":"splitBranch","fieldName":"分流分支","dataType":"STRING"}]','[]','通用分流','[]','LOW',0,0,'按权重进行稳定或随机分流。',1),
('WAIT','等待','等待与汇聚','org.chovy.canvas.engine.handlers.WaitHandler','[{"key":"waitType","label":"等待类型","type":"select","required":true,"defaultValue":"DURATION","options":[{"label":"固定时长","value":"DURATION"},{"label":"直到指定时间","value":"UNTIL_DATE"},{"label":"直到相对时间","value":"RELATIVE_TIME"},{"label":"时间窗口","value":"TIME_WINDOW"},{"label":"直到事件发生","value":"UNTIL_EVENT"}]},{"key":"duration","label":"等待时长","type":"duration","visible":"waitType==DURATION","required":true},{"key":"untilDate","label":"等待到","type":"datetime","visible":"waitType==UNTIL_DATE","required":true},{"key":"time","label":"相对时间","type":"time","visible":"waitType==RELATIVE_TIME","required":true},{"key":"timeWindow","label":"允许窗口","type":"time-window","visible":"waitType==TIME_WINDOW","required":true},{"key":"eventCode","label":"目标事件","type":"select","dataSource":"/meta/event-definitions","visible":"waitType==UNTIL_EVENT","required":true},{"key":"maxWait","label":"最长等待","type":"duration","visible":"waitType==UNTIL_EVENT","required":true}]','[{"fieldKey":"waitStatus","fieldName":"等待结果","dataType":"STRING"}]','[{"id":"success","label":"继续","color":"#52c41a","targetField":"nextNodeId"},{"id":"timeout","label":"超时","color":"#faad14","targetField":"timeoutNodeId"}]','等待（{{waitType}}）','[]','LOW',0,0,'等待一段时间、指定时间窗口或指定事件后继续。',1),
('HUB','集线器','等待与汇聚','org.chovy.canvas.engine.handlers.HubHandler','[{"key":"timeout","label":"等待超时(秒)","type":"number","defaultValue":600}]','[]','[{"id":"success","label":"继续","color":"#52c41a","targetField":"nextNodeId"}]','集线器','[]','LOW',0,0,'等待多条上游路径汇合后继续，不评估结果。',1),
('AGGREGATE','聚合评估','等待与汇聚','org.chovy.canvas.engine.handlers.AggregateHandler','[{"key":"evaluateMode","label":"评估方式","type":"select","required":true,"defaultValue":"count","options":[{"label":"成功数 >= N","value":"count"},{"label":"成功率 >= N%","value":"rate"},{"label":"自定义脚本","value":"script"}]},{"key":"minCount","label":"最少成功数 N","type":"number","defaultValue":1,"visible":"evaluateMode==count"},{"key":"minRate","label":"最低成功率","type":"number","defaultValue":50,"visible":"evaluateMode==rate"},{"key":"evaluateScript","label":"评估脚本","type":"multi-text","visible":"evaluateMode==script"}]','[{"fieldKey":"successCount","fieldName":"成功上游数","dataType":"NUMBER"},{"fieldKey":"failCount","fieldName":"失败上游数","dataType":"NUMBER"},{"fieldKey":"totalCount","fieldName":"上游总数","dataType":"NUMBER"},{"fieldKey":"passed","fieldName":"是否通过评估","dataType":"BOOLEAN"}]','[{"id":"success","label":"条件满足","color":"#52c41a","targetField":"successNodeId"},{"id":"fail","label":"条件不满足","color":"#f5222d","targetField":"failNodeId"}]','聚合评估','[]','MEDIUM',0,0,'等待全部上游完成后汇总评估。',1),
('THRESHOLD','阈值触发','等待与汇聚','org.chovy.canvas.engine.handlers.ThresholdHandler','[{"key":"thresholdMode","label":"触发条件","type":"select","required":true,"defaultValue":"min_success","options":[{"label":"成功数 >= N","value":"min_success"},{"label":"完成数 >= N","value":"min_done"},{"label":"任意上游失败","value":"any_fail"}]},{"key":"threshold","label":"阈值 N","type":"number","defaultValue":1,"visible":"thresholdMode==min_success||thresholdMode==min_done"}]','[{"fieldKey":"successCount","fieldName":"成功上游数","dataType":"NUMBER"},{"fieldKey":"doneCount","fieldName":"已完成上游数","dataType":"NUMBER"},{"fieldKey":"totalCount","fieldName":"上游总数","dataType":"NUMBER"}]','[{"id":"success","label":"达到阈值","color":"#52c41a","targetField":"successNodeId"},{"id":"fail","label":"未达阈值","color":"#f5222d","targetField":"failNodeId"}]','阈值触发','[]','MEDIUM',0,0,'上游完成时流式评估，达到阈值后提前路由。',1),
('API_CALL','接口调用','动作执行','org.chovy.canvas.engine.handlers.ApiCallHandler','[{"key":"bizLineKey","label":"业务线","type":"select","dataSource":"/meta/biz-lines","required":true},{"key":"apiKey","label":"接口","type":"select","dataSource":"/meta/biz-lines/{bizLineKey}/apis","required":true},{"key":"params","label":"请求参数","type":"context-value-list"},{"key":"validateResult","label":"开启结果校验","type":"toggle"},{"key":"validateRules","label":"校验规则","type":"condition-rule-list","visible":"validateResult==true"}]','[]','[{"id":"success","label":"继续","color":"#52c41a","targetField":"nextNodeId"}]','接口调用（{{apiKey}}）','[]','MEDIUM',0,0,'调用外部或内部服务并写回结果。',1),
('SEND_MQ','发送MQ','动作执行','org.chovy.canvas.engine.handlers.SendMqHandler','[{"key":"messageCodeKey","label":"消息类型","type":"select","dataSource":"/meta/message-codes?type=MQ","required":true},{"key":"params","label":"消息参数","type":"context-value-list"}]','[]','[{"id":"success","label":"继续","color":"#52c41a","targetField":"nextNodeId"}]','发送MQ','[]','MEDIUM',0,0,'向下游系统发送业务 MQ。',1),
('GROOVY','Groovy脚本','动作执行','org.chovy.canvas.engine.handlers.GroovyHandler','[{"key":"inputParams","label":"输入参数","type":"context-value-list"},{"key":"code","label":"脚本代码","type":"code-editor","language":"groovy","required":true},{"key":"outputParams","label":"输出参数","type":"param-define-list"},{"key":"validateResult","label":"开启输出校验","type":"toggle"},{"key":"validateRules","label":"校验规则","type":"condition-rule-list","visible":"validateResult==true"}]','[]','[{"id":"success","label":"继续","color":"#52c41a","targetField":"nextNodeId"}]','Groovy脚本','[]','HIGH',0,0,'执行 Groovy 脚本处理复杂逻辑或字段加工。',1),
('SEND_MESSAGE','发送消息','消息触达','org.chovy.canvas.engine.handlers.SendMessageHandler','[{"key":"channel","label":"渠道","type":"select","required":true,"options":[{"label":"邮件","value":"EMAIL"},{"label":"短信","value":"SMS"},{"label":"Push","value":"PUSH"},{"label":"站内信","value":"IN_APP"},{"label":"微信","value":"WECHAT"}]},{"key":"templateId","label":"模板","type":"text"},{"key":"title","label":"标题","type":"text"},{"key":"body","label":"正文","type":"multi-text"},{"key":"variables","label":"变量映射","type":"key-value"}]','[{"fieldKey":"sendRecordId","fieldName":"发送记录ID","dataType":"NUMBER"},{"fieldKey":"sendStatus","fieldName":"发送状态","dataType":"STRING"},{"fieldKey":"externalMessageId","fieldName":"外部消息ID","dataType":"STRING"}]','[{"id":"success","label":"成功","color":"#52c41a","targetField":"successNodeId"},{"id":"fail","label":"失败","color":"#f5222d","targetField":"failNodeId"}]','发送消息（{{channel}}）','[]','HIGH',0,0,'通过统一触达服务发送消息，记录发送结果并支持幂等。',1),
('TAGGER','Tagger 标签','数据与权益','org.chovy.canvas.engine.handlers.TaggerHandler','[{"key":"mode","label":"标签模式","type":"radio","required":true,"options":[{"label":"实时标签","value":"realtime"},{"label":"离线标签","value":"offline"},{"label":"人群圈选","value":"audience"}]},{"key":"tagCodeKey","label":"标签","type":"select","dataSource":"/meta/tagger-tags","required":true,"showWhen":"mode!=audience"},{"key":"audienceId","label":"人群","type":"select","dataSource":"/canvas/audiences/ready","required":true,"showWhen":"mode==audience"}]','[{"fieldKey":"tagValue","fieldName":"标签值","dataType":"STRING"}]','[{"id":"hit","label":"命中","color":"#52c41a","targetField":"hitNextNodeId"},{"id":"miss","label":"未命中","color":"#f5222d","targetField":"missNextNodeId"}]','Tagger 标签','[]','LOW',0,0,'读取或判断用户标签和人群。',1),
('COMMIT_ACTION','提交动作','数据与权益','org.chovy.canvas.engine.handlers.CommitActionHandler','[{"key":"actionType","label":"动作类型","type":"select","required":true,"options":[{"label":"发放代金券","value":"ISSUE_COUPON"},{"label":"积分操作","value":"POINTS"}]},{"key":"couponTypeKey","label":"券类型","type":"select","dataSource":"/meta/coupon-types"},{"key":"params","label":"券参数","type":"dynamic-params","paramsSource":"couponTypeKey"},{"key":"operation","label":"积分操作","type":"select","defaultValue":"GRANT","options":[{"label":"发放","value":"GRANT"},{"label":"扣减","value":"DEDUCT"}]},{"key":"points","label":"积分","type":"number"},{"key":"pointsType","label":"积分类型","type":"text","defaultValue":"MARKETING"},{"key":"idempotencyKey","label":"幂等键","type":"text"}]','[{"fieldKey":"couponAmount","fieldName":"券面额","dataType":"NUMBER"},{"fieldKey":"couponId","fieldName":"券ID","dataType":"STRING"},{"fieldKey":"pointsLedgerId","fieldName":"积分流水ID","dataType":"NUMBER"},{"fieldKey":"duplicate","fieldName":"是否重复","dataType":"BOOLEAN"}]','[{"id":"success","label":"成功","color":"#52c41a","targetField":"nextNodeId"}]','提交动作（{{actionType}}）','[]','HIGH',0,0,'提交权益或关键副作用动作。',1),
('SUB_FLOW_REF','子流程引用','流程复用','org.chovy.canvas.engine.handlers.SubFlowRefHandler','[{"key":"subFlowId","label":"子流程ID","type":"canvas-select","required":true},{"key":"subFlowVersion","label":"版本(-1=最新)","type":"number","defaultValue":-1},{"key":"inputMapping","label":"输入映射","type":"key-value"},{"key":"outputPrefix","label":"输出前缀","type":"input","required":true}]','[]','[{"id":"success","label":"继续","color":"#52c41a","targetField":"nextNodeId"}]','子流程引用','[]','MEDIUM',0,0,'引用已有子流程并写回输出。',1)
ON DUPLICATE KEY UPDATE
  type_name = VALUES(type_name),
  category = VALUES(category),
  handler_class = VALUES(handler_class),
  config_schema = VALUES(config_schema),
  output_schema = VALUES(output_schema),
  outlet_schema = VALUES(outlet_schema),
  summary_template = VALUES(summary_template),
  runtime_policy_schema = VALUES(runtime_policy_schema),
  risk_level = VALUES(risk_level),
  is_trigger = VALUES(is_trigger),
  is_terminal = VALUES(is_terminal),
  description = VALUES(description),
  enabled = VALUES(enabled);
