canvas:
  cors:
    allowed-origins: ${CANVAS_CORS_ALLOWED_ORIGINS}
    allow-credentials: true
  events:
    report-secret: ${CANVAS_EVENT_REPORT_SECRET}
  jwt:
    secret: ${CANVAS_JWT_SECRET}

management:
  endpoint:
    health:
      show-details: when-authorized

springdoc:
  swagger-ui:
    enabled: false
