apiVersion: v1
kind: Service
metadata:
  name: canvas-flink-jobmanager
  namespace: canvas
  labels:
    app.kubernetes.io/name: canvas-flink
    app.kubernetes.io/component: flink-jobmanager
    app.kubernetes.io/part-of: marketing-canvas
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: canvas-flink
    app.kubernetes.io/component: flink-jobmanager
  ports:
    - name: rest
      port: 8081
      targetPort: rest
    - name: rpc
      port: 6123
      targetPort: rpc
