apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: canvas-flink-checkpoints
  namespace: canvas
  labels:
    app.kubernetes.io/name: canvas-flink
    app.kubernetes.io/part-of: marketing-canvas
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: canvas-flink-savepoints
  namespace: canvas
  labels:
    app.kubernetes.io/name: canvas-flink
    app.kubernetes.io/part-of: marketing-canvas
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
