apiVersion: v1
kind: Secret
metadata:
  name: canvas-flink-runtime
  namespace: canvas
  labels:
    app.kubernetes.io/name: canvas-flink
    app.kubernetes.io/part-of: marketing-canvas
type: Opaque
stringData:
  canvas-flink-mysql-url: jdbc:mysql://mysql.data-platform.svc.cluster.local:3306/canvas_db?useSSL=false
  canvas-flink-mysql-username: replace-me
  canvas-flink-mysql-password: replace-me
  canvas-flink-doris-fe-nodes: doris-fe.data-platform.svc.cluster.local:8030
  canvas-flink-doris-be-nodes: doris-be.data-platform.svc.cluster.local:8040
  canvas-flink-doris-jdbc-url: jdbc:mysql://doris-fe.data-platform.svc.cluster.local:9030
  canvas-flink-doris-username: replace-me
  canvas-flink-doris-password: replace-me
  canvas-flink-checkpoint-endpoint: http://canvas-engine.canvas.svc.cluster.local:8080/warehouse/realtime/pipelines/checkpoints
  canvas-flink-internal-api-token: replace-me
