apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: canvas-engine
  namespace: canvas
  labels:
    app.kubernetes.io/name: canvas-engine
    app.kubernetes.io/part-of: marketing-canvas
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: canvas-engine
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
      ports:
        - protocol: TCP
          port: 8080
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - to:
        - namespaceSelector:
            matchLabels:
              app.kubernetes.io/part-of: data-platform
      ports:
        - protocol: TCP
          port: 3306
        - protocol: TCP
          port: 6379
        - protocol: TCP
          port: 9876
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
      ports:
        - protocol: TCP
          port: 9090
