CREATE TABLE IF NOT EXISTS cdp_event_log (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    write_key_id BIGINT NOT NULL,
    message_id VARCHAR(64) NOT NULL,
    event_type VARCHAR(20) NOT NULL DEFAULT 'track',
    event_code VARCHAR(128) NULL,
    user_id VARCHAR(128) NULL,
    anonymous_id VARCHAR(128) NULL,
    session_id VARCHAR(128) NULL,
    device_id VARCHAR(128) NULL,
    platform VARCHAR(32) NULL,
    sdk_context JSON NULL,
    properties JSON NULL,
    idempotency_key VARCHAR(160) NULL,
    event_time DATETIME(3) NOT NULL,
    sent_at DATETIME(3) NULL,
    received_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    status VARCHAR(20) NOT NULL DEFAULT 'ACCEPTED',
    error_message VARCHAR(500) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uk_cdp_event_message (tenant_id, message_id),
    UNIQUE KEY uk_cdp_event_idempotency (tenant_id, idempotency_key),
    INDEX idx_cdp_event_user_time (tenant_id, user_id, event_time),
    INDEX idx_cdp_event_code_time (tenant_id, event_code, event_time),
    INDEX idx_cdp_event_anonymous_time (tenant_id, anonymous_id, event_time),
    INDEX idx_cdp_event_session_time (tenant_id, session_id, event_time),
    INDEX idx_cdp_event_write_key_time (tenant_id, write_key_id, received_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CDP event ingestion log';
