CREATE TABLE IF NOT EXISTS analytics_event (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  tenant_id BIGINT NOT NULL DEFAULT 0,
  event_code VARCHAR(128) NOT NULL,
  user_id VARCHAR(128) NULL,
  anonymous_id VARCHAR(128) NULL,
  session_id VARCHAR(128) NULL,
  platform VARCHAR(64) NULL,
  device_type VARCHAR(64) NULL,
  source VARCHAR(64) NULL,
  event_time DATETIME NOT NULL,
  received_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  schema_version INT NOT NULL DEFAULT 1,
  business_value DECIMAL(18, 4) NULL,
  attributes_json JSON NULL,
  retention_class VARCHAR(32) NOT NULL DEFAULT 'STANDARD',
  archive_status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
  archived_at DATETIME NULL,
  legal_hold TINYINT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_analytics_event_tenant_time (tenant_id, event_time),
  INDEX idx_analytics_event_user_time (tenant_id, user_id, event_time),
  INDEX idx_analytics_event_archive (tenant_id, archive_status),
  INDEX idx_analytics_event_retention (tenant_id, retention_class),
  INDEX idx_analytics_event_code_time (tenant_id, event_code, event_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS analytics_event_trace (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  tenant_id BIGINT NOT NULL DEFAULT 0,
  execution_id VARCHAR(128) NULL,
  canvas_id BIGINT NULL,
  user_id VARCHAR(128) NULL,
  event_code VARCHAR(128) NULL,
  node_id VARCHAR(128) NULL,
  node_type VARCHAR(64) NULL,
  node_name VARCHAR(128) NULL,
  status VARCHAR(32) NULL,
  input_json JSON NULL,
  output_json JSON NULL,
  error_message VARCHAR(1000) NULL,
  started_at DATETIME NULL,
  finished_at DATETIME NULL,
  duration_ms BIGINT NULL,
  event_time DATETIME NOT NULL,
  received_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  schema_version INT NOT NULL DEFAULT 1,
  business_value DECIMAL(18, 4) NULL,
  retention_class VARCHAR(32) NOT NULL DEFAULT 'STANDARD',
  archive_status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
  archived_at DATETIME NULL,
  legal_hold TINYINT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_analytics_trace_tenant_time (tenant_id, event_time),
  INDEX idx_analytics_trace_user_time (tenant_id, user_id, event_time),
  INDEX idx_analytics_trace_archive (tenant_id, archive_status),
  INDEX idx_analytics_trace_retention (tenant_id, retention_class),
  INDEX idx_analytics_trace_execution (tenant_id, execution_id),
  INDEX idx_analytics_trace_canvas_node (tenant_id, canvas_id, node_id, event_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
