CREATE TABLE IF NOT EXISTS cdp_warehouse_table_contract (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    table_key VARCHAR(128) NOT NULL,
    dataset_key VARCHAR(128) NOT NULL,
    layer VARCHAR(32) NOT NULL,
    physical_name VARCHAR(256) NOT NULL,
    engine_type VARCHAR(32) NOT NULL DEFAULT 'DORIS',
    ddl_asset_path VARCHAR(256) DEFAULT NULL,
    partition_column VARCHAR(64) NOT NULL,
    partition_granularity VARCHAR(32) NOT NULL DEFAULT 'DAY',
    retention_days INT NOT NULL,
    replica_count INT NOT NULL DEFAULT 3,
    bucket_count INT NOT NULL,
    distribution_columns VARCHAR(256) NOT NULL,
    storage_policy VARCHAR(128) DEFAULT NULL,
    lifecycle_status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    owner_name VARCHAR(128) DEFAULT NULL,
    description VARCHAR(1000) DEFAULT NULL,
    expected_properties_json JSON DEFAULT NULL,
    last_inspected_at DATETIME DEFAULT NULL,
    last_inspection_status VARCHAR(32) DEFAULT NULL,
    last_inspection_message VARCHAR(1000) DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_cdp_warehouse_table_contract (tenant_id, table_key),
    INDEX idx_cdp_warehouse_table_contract_physical (tenant_id, physical_name),
    INDEX idx_cdp_warehouse_table_contract_dataset (tenant_id, dataset_key),
    INDEX idx_cdp_warehouse_table_contract_status (tenant_id, lifecycle_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CDP warehouse physical table contracts';

CREATE TABLE IF NOT EXISTS cdp_warehouse_table_inspection (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    table_key VARCHAR(128) NOT NULL,
    physical_name VARCHAR(256) NOT NULL,
    status VARCHAR(32) NOT NULL,
    checked_items INT NOT NULL DEFAULT 0,
    violation_count INT NOT NULL DEFAULT 0,
    message VARCHAR(1000) DEFAULT NULL,
    violations_json JSON DEFAULT NULL,
    ddl_asset_path VARCHAR(256) DEFAULT NULL,
    inspected_by VARCHAR(128) DEFAULT NULL,
    inspected_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_cdp_warehouse_table_inspection_table (tenant_id, table_key, inspected_at),
    INDEX idx_cdp_warehouse_table_inspection_status (tenant_id, status, inspected_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CDP warehouse physical table inspection evidence';

INSERT INTO cdp_warehouse_table_contract
(tenant_id, table_key, dataset_key, layer, physical_name, engine_type, ddl_asset_path,
 partition_column, partition_granularity, retention_days, replica_count, bucket_count,
 distribution_columns, storage_policy, lifecycle_status, owner_name, description, expected_properties_json)
VALUES
(0, 'cdp_ods_event_log', 'cdp_ods_event_log', 'ODS', 'canvas_ods.cdp_event_log', 'DORIS',
 'infrastructure/doris/cdp-audience-ddl.sql', 'event_time', 'DAY', 90, 3, 16,
 'tenant_id,event_code', NULL, 'ACTIVE', 'data-platform',
 'Accepted CDP events mirrored into Doris ODS with day partitions.',
 JSON_OBJECT('dynamic_partition', true, 'retention_days', 90)),
(0, 'cdp_dwd_user_event_fact', 'cdp_dwd_user_event_fact', 'DWD', 'canvas_dwd.cdp_user_event_fact', 'DORIS',
 'infrastructure/doris/cdp-audience-ddl.sql', 'event_date', 'DAY', 180, 3, 32,
 'tenant_id,user_id', NULL, 'ACTIVE', 'data-platform',
 'User-level event fact table derived from CDP ODS events.',
 JSON_OBJECT('dynamic_partition', true, 'retention_days', 180)),
(0, 'cdp_dws_user_event_metric_daily', 'cdp_dws_user_event_metric_daily', 'DWS', 'canvas_dws.user_event_metric_daily', 'DORIS',
 'infrastructure/doris/cdp-audience-ddl.sql', 'stat_date', 'DAY', 730, 3, 32,
 'tenant_id,user_id', NULL, 'ACTIVE', 'data-platform',
 'Daily per-user event metric aggregate table.',
 JSON_OBJECT('dynamic_partition', true, 'retention_days', 730)),
(0, 'canvas_execution_trace', 'canvas_execution_trace', 'ODS', 'canvas_ods.canvas_execution_trace', 'DORIS',
 'infrastructure/doris/trace-ddl.sql', 'created_at', 'DAY', 90, 3, 8,
 'execution_id', NULL, 'ACTIVE', 'data-platform',
 'Canvas execution trace rows streamed to Doris ODS.',
 JSON_OBJECT('dynamic_partition', true, 'retention_days', 90)),
(0, 'canvas_daily_stats', 'canvas_daily_stats', 'DWS', 'canvas_dws.canvas_daily_stats', 'DORIS',
 'infrastructure/doris/trace-ddl.sql', 'stat_date', 'DAY', 730, 3, 8,
 'canvas_id', NULL, 'ACTIVE', 'data-platform',
 'Daily canvas execution stats aggregate table.',
 JSON_OBJECT('dynamic_partition', true, 'retention_days', 730)),
(0, 'node_daily_stats', 'node_daily_stats', 'DWS', 'canvas_dws.node_daily_stats', 'DORIS',
 'infrastructure/doris/trace-ddl.sql', 'stat_date', 'DAY', 730, 3, 8,
 'canvas_id', NULL, 'ACTIVE', 'data-platform',
 'Daily canvas node execution stats aggregate table.',
 JSON_OBJECT('dynamic_partition', true, 'retention_days', 730))
ON DUPLICATE KEY UPDATE
    dataset_key = VALUES(dataset_key),
    layer = VALUES(layer),
    physical_name = VALUES(physical_name),
    engine_type = VALUES(engine_type),
    ddl_asset_path = VALUES(ddl_asset_path),
    partition_column = VALUES(partition_column),
    partition_granularity = VALUES(partition_granularity),
    retention_days = VALUES(retention_days),
    replica_count = VALUES(replica_count),
    bucket_count = VALUES(bucket_count),
    distribution_columns = VALUES(distribution_columns),
    storage_policy = VALUES(storage_policy),
    lifecycle_status = VALUES(lifecycle_status),
    owner_name = VALUES(owner_name),
    description = VALUES(description),
    expected_properties_json = VALUES(expected_properties_json),
    updated_at = CURRENT_TIMESTAMP;
