CREATE TABLE IF NOT EXISTS cdp_warehouse_field_policy (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    dataset_key VARCHAR(128) NOT NULL,
    field_key VARCHAR(128) NOT NULL,
    physical_name VARCHAR(256) NOT NULL,
    column_name VARCHAR(128) NOT NULL,
    value_type VARCHAR(32) NOT NULL,
    semantic_type VARCHAR(64) DEFAULT NULL,
    pii_level VARCHAR(32) NOT NULL DEFAULT 'NORMAL',
    access_policy VARCHAR(32) NOT NULL DEFAULT 'ALLOW',
    min_role VARCHAR(64) NOT NULL DEFAULT 'OPERATOR',
    allowed_usages VARCHAR(256) NOT NULL DEFAULT 'SELECT,FILTER,SORT,GROUP',
    mask_strategy VARCHAR(64) DEFAULT NULL,
    lifecycle_status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    owner_name VARCHAR(128) DEFAULT NULL,
    description VARCHAR(1000) DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_cdp_warehouse_field_policy (tenant_id, dataset_key, field_key),
    INDEX idx_cdp_warehouse_field_policy_dataset (tenant_id, dataset_key, lifecycle_status),
    INDEX idx_cdp_warehouse_field_policy_pii (tenant_id, pii_level, access_policy)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CDP warehouse field-level governance policy';

CREATE TABLE IF NOT EXISTS cdp_warehouse_field_access_audit (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    dataset_key VARCHAR(128) NOT NULL,
    field_key VARCHAR(128) NOT NULL,
    actor_id VARCHAR(128) DEFAULT NULL,
    actor_role VARCHAR(64) DEFAULT NULL,
    action_key VARCHAR(64) NOT NULL,
    decision VARCHAR(32) NOT NULL,
    reason VARCHAR(1000) DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_cdp_warehouse_field_audit_dataset (tenant_id, dataset_key, created_at),
    INDEX idx_cdp_warehouse_field_audit_actor (tenant_id, actor_id, created_at),
    INDEX idx_cdp_warehouse_field_audit_decision (tenant_id, decision, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CDP warehouse denied field access audit';

INSERT INTO cdp_warehouse_field_policy
(tenant_id, dataset_key, field_key, physical_name, column_name, value_type, semantic_type, pii_level,
 access_policy, min_role, allowed_usages, mask_strategy, lifecycle_status, owner_name, description)
VALUES
(0, 'canvas_daily_stats', 'stat_date', 'canvas_dws.canvas_daily_stats', 'stat_date', 'DATE', 'DATE',
 'NORMAL', 'ALLOW', 'OPERATOR', 'SELECT,FILTER,SORT,GROUP', NULL, 'ACTIVE', 'data-platform', 'BI stat date.'),
(0, 'canvas_daily_stats', 'canvas_id', 'canvas_dws.canvas_daily_stats', 'canvas_id', 'NUMBER', 'ID',
 'NORMAL', 'ALLOW', 'OPERATOR', 'SELECT,FILTER,SORT,GROUP', NULL, 'ACTIVE', 'data-platform', 'Canvas id.'),
(0, 'canvas_daily_stats', 'canvas_name', 'canvas_dws.canvas_daily_stats', 'canvas_name', 'STRING', 'NAME',
 'NORMAL', 'ALLOW', 'OPERATOR', 'SELECT,FILTER,SORT,GROUP', NULL, 'ACTIVE', 'data-platform', 'Canvas display name.'),
(0, 'canvas_daily_stats', 'trigger_type', 'canvas_dws.canvas_daily_stats', 'trigger_type', 'STRING', 'CATEGORY',
 'NORMAL', 'ALLOW', 'OPERATOR', 'SELECT,FILTER,SORT,GROUP', NULL, 'ACTIVE', 'data-platform', 'Canvas trigger type.'),
(0, 'canvas_daily_stats', 'total_executions', 'canvas_dws.canvas_daily_stats', 'total_executions', 'NUMBER', 'COUNT',
 'NORMAL', 'ALLOW', 'OPERATOR', 'SELECT', NULL, 'ACTIVE', 'data-platform', 'Execution count metric source.'),
(0, 'canvas_daily_stats', 'success_count', 'canvas_dws.canvas_daily_stats', 'success_count', 'NUMBER', 'COUNT',
 'NORMAL', 'ALLOW', 'OPERATOR', 'SELECT', NULL, 'ACTIVE', 'data-platform', 'Success count metric source.'),
(0, 'canvas_daily_stats', 'fail_count', 'canvas_dws.canvas_daily_stats', 'fail_count', 'NUMBER', 'COUNT',
 'NORMAL', 'ALLOW', 'OPERATOR', 'SELECT', NULL, 'ACTIVE', 'data-platform', 'Failure count metric source.'),
(0, 'canvas_daily_stats', 'unique_users', 'canvas_dws.canvas_daily_stats', 'unique_users', 'NUMBER', 'COUNT',
 'AGGREGATED_USER', 'ALLOW', 'OPERATOR', 'SELECT', NULL, 'ACTIVE', 'data-platform', 'Aggregated unique user count.'),
(0, 'cdp_ods_event_log', 'user_id', 'canvas_ods.cdp_event_log', 'user_id', 'STRING', 'USER_ID',
 'PII_RELATED', 'MASK', 'TENANT_ADMIN', 'SELECT,FILTER,GROUP', 'HASH', 'ACTIVE', 'data-platform', 'CDP user id.'),
(0, 'cdp_ods_event_log', 'anonymous_id', 'canvas_ods.cdp_event_log', 'anonymous_id', 'STRING', 'ANONYMOUS_ID',
 'PII_RELATED', 'MASK', 'TENANT_ADMIN', 'SELECT,FILTER,GROUP', 'HASH', 'ACTIVE', 'data-platform', 'Anonymous visitor id.'),
(0, 'cdp_ods_event_log', 'device_id', 'canvas_ods.cdp_event_log', 'device_id', 'STRING', 'DEVICE_ID',
 'PII_RELATED', 'MASK', 'TENANT_ADMIN', 'SELECT,FILTER,GROUP', 'HASH', 'ACTIVE', 'data-platform', 'Device id.'),
(0, 'cdp_ods_event_log', 'properties', 'canvas_ods.cdp_event_log', 'properties', 'JSON', 'EVENT_PROPERTIES',
 'PII_RELATED', 'MASK', 'TENANT_ADMIN', 'SELECT,FILTER', 'JSON_REDACT', 'ACTIVE', 'data-platform', 'Raw event properties may contain PII.'),
(0, 'cdp_dwd_user_event_fact', 'user_id', 'canvas_dwd.cdp_user_event_fact', 'user_id', 'STRING', 'USER_ID',
 'PII_RELATED', 'MASK', 'TENANT_ADMIN', 'SELECT,FILTER,GROUP', 'HASH', 'ACTIVE', 'data-platform', 'DWD user id.'),
(0, 'cdp_dwd_user_event_fact', 'properties_json', 'canvas_dwd.cdp_user_event_fact', 'properties_json', 'STRING', 'EVENT_PROPERTIES',
 'PII_RELATED', 'MASK', 'TENANT_ADMIN', 'SELECT,FILTER', 'JSON_REDACT', 'ACTIVE', 'data-platform', 'DWD event properties JSON.'),
(0, 'cdp_dws_user_event_metric_daily', 'user_id', 'canvas_dws.user_event_metric_daily', 'user_id', 'STRING', 'USER_ID',
 'PII_RELATED', 'MASK', 'TENANT_ADMIN', 'SELECT,FILTER,GROUP', 'HASH', 'ACTIVE', 'data-platform', 'DWS user id.')
ON DUPLICATE KEY UPDATE
    physical_name = VALUES(physical_name),
    column_name = VALUES(column_name),
    value_type = VALUES(value_type),
    semantic_type = VALUES(semantic_type),
    pii_level = VALUES(pii_level),
    access_policy = VALUES(access_policy),
    min_role = VALUES(min_role),
    allowed_usages = VALUES(allowed_usages),
    mask_strategy = VALUES(mask_strategy),
    lifecycle_status = VALUES(lifecycle_status),
    owner_name = VALUES(owner_name),
    description = VALUES(description),
    updated_at = CURRENT_TIMESTAMP;
