CREATE TABLE IF NOT EXISTS bi_delivery_attachment (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  tenant_id BIGINT NOT NULL DEFAULT 0,
  workspace_id BIGINT NOT NULL,
  job_type VARCHAR(32) NOT NULL,
  job_id BIGINT NOT NULL,
  job_key VARCHAR(128) NOT NULL,
  delivery_log_id BIGINT NULL,
  resource_type VARCHAR(64) NULL,
  resource_id BIGINT NULL,
  attachment_key VARCHAR(160) NOT NULL,
  attachment_type VARCHAR(32) NOT NULL,
  file_name VARCHAR(255) NOT NULL,
  content_type VARCHAR(255) NOT NULL,
  file_path VARCHAR(1000) NULL,
  file_url VARCHAR(1000) NULL,
  size_bytes BIGINT NULL,
  status VARCHAR(32) NOT NULL,
  error_message VARCHAR(1000) NULL,
  created_by VARCHAR(128) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_bi_delivery_attachment_key (tenant_id, attachment_key),
  INDEX idx_bi_delivery_attachment_job (tenant_id, job_type, job_id, created_at),
  INDEX idx_bi_delivery_attachment_log (tenant_id, delivery_log_id),
  INDEX idx_bi_delivery_attachment_status (tenant_id, status, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
