CREATE TABLE IF NOT EXISTS cdp_warehouse_privacy_audience_rebuild_automation_run (
    id BIGINT NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT NOT NULL,
    trigger_source VARCHAR(32) NOT NULL,
    status VARCHAR(16) NOT NULL,
    actor VARCHAR(128) NULL,
    scan_limit INT NULL,
    audience_limit INT NULL,
    retry_failed TINYINT NOT NULL DEFAULT 0,
    scanned INT NOT NULL DEFAULT 0,
    eligible INT NOT NULL DEFAULT 0,
    triggered INT NOT NULL DEFAULT 0,
    skipped INT NOT NULL DEFAULT 0,
    failed INT NOT NULL DEFAULT 0,
    result_json MEDIUMTEXT NULL,
    error_message VARCHAR(1024) NULL,
    started_at DATETIME NOT NULL,
    finished_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_cdp_warehouse_privacy_audience_rebuild_run_status (tenant_id, status, started_at),
    INDEX idx_cdp_warehouse_privacy_audience_rebuild_run_source (tenant_id, trigger_source, started_at),
    INDEX idx_cdp_warehouse_privacy_audience_rebuild_run_started (tenant_id, started_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CDP warehouse privacy audience bitmap rebuild automation run history';
