CREATE TABLE IF NOT EXISTS marketing_asset_folder (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  folder_key VARCHAR(128) NOT NULL,
  name VARCHAR(200) NOT NULL,
  parent_id BIGINT NULL,
  created_by VARCHAR(128) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_marketing_asset_folder_key (tenant_id, folder_key),
  INDEX idx_marketing_asset_folder_parent (tenant_id, parent_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Marketing content hub asset folders';

CREATE TABLE IF NOT EXISTS marketing_asset (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  asset_key VARCHAR(128) NOT NULL,
  name VARCHAR(200) NOT NULL,
  asset_type VARCHAR(32) NOT NULL,
  mime_type VARCHAR(128) NOT NULL,
  storage_url VARCHAR(1000) NOT NULL,
  folder_id BIGINT NULL,
  size_bytes BIGINT NULL,
  checksum_sha256 VARCHAR(128) NULL,
  thumbnail_url VARCHAR(1000) NULL,
  poster_url VARCHAR(1000) NULL,
  width INT NULL,
  height INT NULL,
  duration_ms BIGINT NULL,
  transcode_status VARCHAR(32) NULL,
  tags_json JSON NOT NULL,
  metadata_json JSON NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
  review_notes VARCHAR(1000) NULL,
  reference_count INT NOT NULL DEFAULT 0,
  created_by VARCHAR(128) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_marketing_asset_key (tenant_id, asset_key),
  INDEX idx_marketing_asset_search (tenant_id, asset_type, status, updated_at),
  INDEX idx_marketing_asset_folder (tenant_id, folder_id),
  INDEX idx_marketing_asset_status (tenant_id, status, updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Marketing DAM asset metadata';

CREATE TABLE IF NOT EXISTS marketing_content_template (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  template_key VARCHAR(128) NOT NULL,
  display_name VARCHAR(200) NOT NULL,
  channel VARCHAR(32) NOT NULL,
  subject VARCHAR(500) NULL,
  body MEDIUMTEXT NOT NULL,
  design_json JSON NOT NULL,
  asset_refs_json JSON NOT NULL,
  variables_json JSON NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
  review_notes VARCHAR(1000) NULL,
  created_by VARCHAR(128) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_marketing_content_template_key (tenant_id, template_key),
  INDEX idx_marketing_template_search (tenant_id, channel, status, updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Marketing content template design records';

CREATE TABLE IF NOT EXISTS marketing_content_template_version (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  template_key VARCHAR(128) NOT NULL,
  version_no INT NOT NULL,
  display_name VARCHAR(200) NOT NULL,
  channel VARCHAR(32) NOT NULL,
  subject VARCHAR(500) NULL,
  body MEDIUMTEXT NOT NULL,
  design_json JSON NOT NULL,
  asset_refs_json JSON NOT NULL,
  variables_json JSON NOT NULL,
  status VARCHAR(32) NOT NULL,
  created_by VARCHAR(128) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_marketing_template_version (tenant_id, template_key, version_no),
  INDEX idx_marketing_template_version_key (tenant_id, template_key, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Marketing content template immutable versions';

CREATE TABLE IF NOT EXISTS marketing_content_entry (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  entry_key VARCHAR(128) NOT NULL,
  content_type VARCHAR(64) NOT NULL,
  title VARCHAR(200) NOT NULL,
  slug VARCHAR(200) NULL,
  locale VARCHAR(32) NULL,
  summary VARCHAR(1000) NULL,
  body_json JSON NOT NULL,
  seo_json JSON NOT NULL,
  asset_refs_json JSON NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
  published_at DATETIME NULL,
  created_by VARCHAR(128) NOT NULL,
  updated_by VARCHAR(128) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_marketing_content_entry_key (tenant_id, entry_key),
  UNIQUE KEY uk_marketing_content_entry_slug (tenant_id, content_type, locale, slug),
  INDEX idx_marketing_entry_search (tenant_id, content_type, status, updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Marketing CMS-style content entries';

CREATE TABLE IF NOT EXISTS marketing_content_entry_version (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  entry_key VARCHAR(128) NOT NULL,
  version_no INT NOT NULL,
  content_type VARCHAR(64) NOT NULL,
  title VARCHAR(200) NOT NULL,
  slug VARCHAR(200) NULL,
  locale VARCHAR(32) NULL,
  summary VARCHAR(1000) NULL,
  body_json JSON NOT NULL,
  seo_json JSON NOT NULL,
  asset_refs_json JSON NOT NULL,
  status VARCHAR(32) NOT NULL,
  created_by VARCHAR(128) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_marketing_entry_version (tenant_id, entry_key, version_no),
  INDEX idx_marketing_entry_version_key (tenant_id, entry_key, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Marketing content entry immutable versions';
