CREATE TABLE IF NOT EXISTS ai_decision_run (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  model_key VARCHAR(80) NOT NULL,
  model_version VARCHAR(80) NOT NULL,
  decision_scope VARCHAR(80) NOT NULL,
  run_date DATE NOT NULL,
  status VARCHAR(32) NOT NULL,
  requested_count INT NOT NULL DEFAULT 0,
  processed_count INT NOT NULL DEFAULT 0,
  skipped_count INT NOT NULL DEFAULT 0,
  failed_count INT NOT NULL DEFAULT 0,
  metadata_json JSON NULL,
  created_by VARCHAR(128) NULL,
  started_at DATETIME NULL,
  finished_at DATETIME NULL,
  error_message VARCHAR(1000) NULL,
  created_at DATETIME NULL,
  updated_at DATETIME NULL,
  UNIQUE KEY uk_ai_decision_run (tenant_id, model_key, model_version, decision_scope, run_date),
  KEY idx_ai_decision_run_status (tenant_id, decision_scope, status, started_at),
  KEY idx_ai_decision_run_latest (tenant_id, decision_scope, started_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI decision model run ledger';

CREATE TABLE IF NOT EXISTS ai_user_decision_recommendation (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  run_id BIGINT NOT NULL,
  user_id VARCHAR(128) NOT NULL,
  model_key VARCHAR(80) NOT NULL,
  model_version VARCHAR(80) NOT NULL,
  decision_scope VARCHAR(80) NOT NULL,
  decision_type VARCHAR(64) NOT NULL,
  decision_key VARCHAR(128) NOT NULL,
  action_key VARCHAR(128) NULL,
  offer_key VARCHAR(128) NULL,
  channel VARCHAR(64) NULL,
  score DECIMAL(8,5) NOT NULL DEFAULT 0.00000,
  confidence DECIMAL(6,5) NOT NULL DEFAULT 0.50000,
  recommendation_rank INT NOT NULL DEFAULT 0,
  budget_cost DECIMAL(14,4) NOT NULL DEFAULT 0.0000,
  eligibility_status VARCHAR(32) NOT NULL,
  fallback_reason VARCHAR(256) NULL,
  feature_json JSON NOT NULL,
  explanation_json JSON NOT NULL,
  created_at DATETIME NULL,
  updated_at DATETIME NULL,
  UNIQUE KEY uk_ai_decision_reco_user_type_key (tenant_id, run_id, user_id, decision_type, decision_key),
  KEY idx_ai_decision_reco_type_rank (tenant_id, decision_type, eligibility_status, recommendation_rank, score),
  KEY idx_ai_decision_reco_user (tenant_id, user_id, created_at),
  KEY idx_ai_decision_reco_run (tenant_id, run_id, recommendation_rank)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI user decision recommendations and explanations';

CREATE TABLE IF NOT EXISTS ai_decision_feedback (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  recommendation_id BIGINT NOT NULL,
  feedback_type VARCHAR(64) NOT NULL,
  outcome_value DECIMAL(14,4) NULL,
  metadata_json JSON NULL,
  created_by VARCHAR(128) NULL,
  occurred_at DATETIME NOT NULL,
  created_at DATETIME NULL,
  KEY idx_ai_decision_feedback_reco (tenant_id, recommendation_id, occurred_at),
  KEY idx_ai_decision_feedback_type (tenant_id, feedback_type, occurred_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI decision recommendation feedback and outcomes';
