CREATE TABLE IF NOT EXISTS marketing_monitor_alert_channel (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  channel_key VARCHAR(128) NOT NULL,
  channel_type VARCHAR(64) NOT NULL,
  display_name VARCHAR(256) NOT NULL,
  endpoint_url VARCHAR(1000) NOT NULL,
  enabled TINYINT NOT NULL DEFAULT 1,
  min_severity VARCHAR(32) NOT NULL DEFAULT 'LOW',
  alert_types_json JSON NULL,
  signing_mode VARCHAR(64) NOT NULL DEFAULT 'NONE',
  secret_prefix VARCHAR(16) NULL,
  secret_hash VARCHAR(120) NULL,
  secret_ciphertext VARCHAR(1000) NULL,
  metadata_json JSON NULL,
  max_attempts INT NOT NULL DEFAULT 3,
  created_by VARCHAR(128) NULL,
  created_at DATETIME NULL,
  updated_at DATETIME NULL,
  UNIQUE KEY uk_marketing_monitor_alert_channel (tenant_id, channel_key),
  KEY idx_marketing_monitor_alert_channel_enabled (tenant_id, enabled, min_severity),
  KEY idx_marketing_monitor_alert_channel_type (tenant_id, channel_type, enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='External fanout channels for marketing monitoring alerts';

CREATE TABLE IF NOT EXISTS marketing_monitor_alert_delivery (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  alert_id BIGINT NOT NULL,
  channel_id BIGINT NOT NULL,
  channel_key VARCHAR(128) NOT NULL,
  channel_type VARCHAR(64) NOT NULL,
  delivery_id VARCHAR(64) NOT NULL,
  attempt INT NOT NULL DEFAULT 1,
  http_status INT NULL,
  request_payload JSON NULL,
  response_body TEXT NULL,
  status VARCHAR(32) NOT NULL,
  next_retry_at DATETIME NULL,
  error_message VARCHAR(1000) NULL,
  terminal_reason VARCHAR(256) NULL,
  created_by VARCHAR(128) NULL,
  created_at DATETIME NULL,
  updated_at DATETIME NULL,
  UNIQUE KEY uk_marketing_monitor_alert_delivery (tenant_id, delivery_id),
  KEY idx_marketing_monitor_alert_delivery_status (tenant_id, status, created_at),
  KEY idx_marketing_monitor_alert_delivery_alert (tenant_id, alert_id, created_at),
  KEY idx_marketing_monitor_alert_delivery_channel (tenant_id, channel_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Delivery attempts for monitoring alert fanout';
