CREATE TABLE IF NOT EXISTS conversation_ai_reply_suggestion (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT 'Tenant id',
    work_item_id BIGINT NOT NULL COMMENT 'SCRM work item id',
    session_id BIGINT NOT NULL COMMENT 'Conversation session id',
    source_message_id BIGINT NULL COMMENT 'Latest inbound source message id used for the suggestion',
    prompt_context_json JSON NULL COMMENT 'Prompt context assembled from timeline and work item state',
    suggested_reply_text TEXT NOT NULL COMMENT 'AI suggested reply draft',
    tone VARCHAR(64) NULL COMMENT 'Suggested reply tone',
    intent VARCHAR(128) NULL COMMENT 'Suggested reply intent',
    confidence DECIMAL(5,4) NOT NULL DEFAULT 0.0000 COMMENT 'Generator confidence from 0 to 1',
    risk_flags_json JSON NULL COMMENT 'Risk flags requiring operator attention',
    grounding_snippets_json JSON NULL COMMENT 'Conversation snippets used to ground the draft',
    provider_id BIGINT NULL COMMENT 'AI provider id when available',
    template_id BIGINT NULL COMMENT 'AI prompt template id when available',
    model_key VARCHAR(128) NULL COMMENT 'AI model key',
    provider_status VARCHAR(64) NULL COMMENT 'Gateway or generator status',
    fallback_used TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'Whether a fallback result was used',
    status VARCHAR(32) NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT/ACCEPTED/REJECTED/EXPIRED',
    generated_by VARCHAR(128) NOT NULL DEFAULT 'system' COMMENT 'Operator or system actor',
    reviewed_by VARCHAR(128) NULL COMMENT 'Reviewing operator',
    reviewed_at DATETIME NULL COMMENT 'Review time',
    review_note VARCHAR(512) NULL COMMENT 'Review note',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_conversation_ai_reply_work_item (tenant_id, work_item_id, created_at),
    INDEX idx_conversation_ai_reply_status (tenant_id, status, created_at),
    INDEX idx_conversation_ai_reply_review (tenant_id, reviewed_by, reviewed_at),
    INDEX idx_conversation_ai_reply_source_message (tenant_id, source_message_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='SCRM AI reply suggestions';
