ALTER TABLE marketing_monitor_source
  ADD COLUMN poll_enabled TINYINT NOT NULL DEFAULT 0 AFTER webhook_signature_tolerance_seconds,
  ADD COLUMN poll_interval_minutes INT NOT NULL DEFAULT 60 AFTER poll_enabled,
  ADD COLUMN poll_cursor VARCHAR(1000) NULL AFTER poll_interval_minutes,
  ADD COLUMN last_polled_at DATETIME NULL AFTER poll_cursor,
  ADD COLUMN next_poll_at DATETIME NULL AFTER last_polled_at,
  ADD COLUMN last_poll_status VARCHAR(32) NULL AFTER next_poll_at,
  ADD INDEX idx_marketing_monitor_source_polling (tenant_id, poll_enabled, enabled, next_poll_at);

CREATE TABLE IF NOT EXISTS marketing_monitor_poll_run (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  source_id BIGINT NOT NULL,
  source_key VARCHAR(128) NOT NULL,
  source_type VARCHAR(64) NOT NULL,
  status VARCHAR(32) NOT NULL,
  requested_from DATETIME NULL,
  requested_until DATETIME NULL,
  cursor_before VARCHAR(1000) NULL,
  cursor_after VARCHAR(1000) NULL,
  item_count INT NOT NULL DEFAULT 0,
  inserted_count INT NOT NULL DEFAULT 0,
  duplicate_count INT NOT NULL DEFAULT 0,
  alert_count INT NOT NULL DEFAULT 0,
  error_message VARCHAR(1000) NULL,
  metadata_json JSON NULL,
  created_by VARCHAR(128) NULL,
  started_at DATETIME NOT NULL,
  finished_at DATETIME NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  KEY idx_marketing_monitor_poll_run_source (tenant_id, source_id, started_at),
  KEY idx_marketing_monitor_poll_run_status (tenant_id, status, started_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Marketing monitoring provider polling run ledger';

CREATE TABLE IF NOT EXISTS marketing_monitor_trend_snapshot (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  source_id BIGINT NOT NULL,
  source_key VARCHAR(128) NOT NULL,
  bucket_grain VARCHAR(32) NOT NULL,
  bucket_start DATETIME NOT NULL,
  bucket_end DATETIME NOT NULL,
  brand_key VARCHAR(128) NULL,
  competitor_key VARCHAR(128) NULL,
  mention_count INT NOT NULL DEFAULT 0,
  positive_count INT NOT NULL DEFAULT 0,
  neutral_count INT NOT NULL DEFAULT 0,
  negative_count INT NOT NULL DEFAULT 0,
  competitor_count INT NOT NULL DEFAULT 0,
  alert_count INT NOT NULL DEFAULT 0,
  avg_sentiment_score DECIMAL(8,5) NOT NULL DEFAULT 0.00000,
  metadata_json JSON NULL,
  created_by VARCHAR(128) NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  UNIQUE KEY uk_marketing_monitor_trend_snapshot (tenant_id, source_id, bucket_grain, bucket_start, brand_key, competitor_key),
  KEY idx_marketing_monitor_trend_scope (tenant_id, source_id, bucket_start, brand_key, competitor_key),
  KEY idx_marketing_monitor_trend_created (tenant_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Marketing monitoring trend snapshots';
