CREATE TABLE IF NOT EXISTS `programmatic_dsp_seat` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `tenant_id` BIGINT NOT NULL,
  `provider` VARCHAR(64) NOT NULL,
  `seat_key` VARCHAR(128) NOT NULL,
  `display_name` VARCHAR(255) NOT NULL,
  `advertiser_account_id` VARCHAR(128) NULL,
  `currency` VARCHAR(16) NOT NULL DEFAULT 'CNY',
  `timezone` VARCHAR(64) NOT NULL DEFAULT 'UTC',
  `supply_chain_enforcement` VARCHAR(32) NOT NULL DEFAULT 'MONITOR',
  `enabled` TINYINT NOT NULL DEFAULT 1,
  `metadata_json` JSON NULL,
  `created_by` VARCHAR(128) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `uk_programmatic_dsp_seat_identity` (`tenant_id`, `provider`, `seat_key`),
  KEY `idx_programmatic_dsp_seat_enabled` (`tenant_id`, `enabled`, `provider`),
  KEY `idx_programmatic_dsp_seat_updated` (`tenant_id`, `updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Programmatic DSP seat and advertiser account registry';

CREATE TABLE IF NOT EXISTS `programmatic_dsp_campaign` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `tenant_id` BIGINT NOT NULL,
  `campaign_key` VARCHAR(128) NOT NULL,
  `campaign_name` VARCHAR(255) NOT NULL,
  `objective` VARCHAR(64) NULL,
  `budget_amount` DECIMAL(18,4) NOT NULL DEFAULT 0.0000,
  `currency` VARCHAR(16) NOT NULL DEFAULT 'CNY',
  `start_at` DATETIME NULL,
  `end_at` DATETIME NULL,
  `status` VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
  `metadata_json` JSON NULL,
  `created_by` VARCHAR(128) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `uk_programmatic_dsp_campaign_key` (`tenant_id`, `campaign_key`),
  KEY `idx_programmatic_dsp_campaign_status` (`tenant_id`, `status`, `start_at`, `end_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Programmatic DSP campaign or insertion-order-like flights';

CREATE TABLE IF NOT EXISTS `programmatic_dsp_line_item` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `tenant_id` BIGINT NOT NULL,
  `seat_id` BIGINT NOT NULL,
  `campaign_id` BIGINT NOT NULL,
  `line_item_key` VARCHAR(128) NOT NULL,
  `line_item_name` VARCHAR(255) NOT NULL,
  `bid_strategy` VARCHAR(64) NOT NULL DEFAULT 'MANUAL_CPM',
  `max_bid_cpm` DECIMAL(18,4) NOT NULL DEFAULT 0.0000,
  `daily_budget_amount` DECIMAL(18,4) NOT NULL DEFAULT 0.0000,
  `total_budget_amount` DECIMAL(18,4) NOT NULL DEFAULT 0.0000,
  `pacing_mode` VARCHAR(32) NOT NULL DEFAULT 'EVEN',
  `targeting_json` JSON NULL,
  `frequency_cap` INT NOT NULL DEFAULT 0,
  `status` VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
  `metadata_json` JSON NULL,
  `created_by` VARCHAR(128) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `uk_programmatic_dsp_line_item_key` (`tenant_id`, `campaign_id`, `line_item_key`),
  KEY `idx_programmatic_dsp_line_item_seat` (`tenant_id`, `seat_id`, `status`),
  KEY `idx_programmatic_dsp_line_item_campaign` (`tenant_id`, `campaign_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Programmatic DSP line item commercial controls and targeting';

CREATE TABLE IF NOT EXISTS `programmatic_dsp_supply_path` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `tenant_id` BIGINT NOT NULL,
  `line_item_id` BIGINT NOT NULL,
  `exchange_key` VARCHAR(128) NOT NULL,
  `deal_id` VARCHAR(128) NOT NULL DEFAULT '',
  `seller_id` VARCHAR(128) NOT NULL DEFAULT '',
  `seller_domain` VARCHAR(255) NULL,
  `inventory_type` VARCHAR(64) NULL,
  `ads_txt_status` VARCHAR(32) NOT NULL DEFAULT 'UNKNOWN',
  `sellers_json_status` VARCHAR(32) NOT NULL DEFAULT 'UNKNOWN',
  `schain_complete` TINYINT NOT NULL DEFAULT 0,
  `status` VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
  `metadata_json` JSON NULL,
  `created_by` VARCHAR(128) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `uk_programmatic_dsp_supply_path_identity` (`tenant_id`, `line_item_id`, `exchange_key`, `deal_id`, `seller_id`),
  KEY `idx_programmatic_dsp_supply_path_status` (`tenant_id`, `status`, `ads_txt_status`, `sellers_json_status`),
  KEY `idx_programmatic_dsp_supply_path_line_item` (`tenant_id`, `line_item_id`, `exchange_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Programmatic DSP supply path transparency and deal governance';

CREATE TABLE IF NOT EXISTS `programmatic_dsp_performance_snapshot` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `tenant_id` BIGINT NOT NULL,
  `seat_id` BIGINT NOT NULL,
  `campaign_id` BIGINT NOT NULL,
  `line_item_id` BIGINT NOT NULL,
  `snapshot_date` DATE NOT NULL,
  `bid_count` BIGINT NOT NULL DEFAULT 0,
  `win_count` BIGINT NOT NULL DEFAULT 0,
  `impression_count` BIGINT NOT NULL DEFAULT 0,
  `click_count` BIGINT NOT NULL DEFAULT 0,
  `conversion_count` BIGINT NOT NULL DEFAULT 0,
  `viewable_impression_count` BIGINT NOT NULL DEFAULT 0,
  `spend_amount` DECIMAL(18,4) NOT NULL DEFAULT 0.0000,
  `revenue_amount` DECIMAL(18,4) NOT NULL DEFAULT 0.0000,
  `metadata_json` JSON NULL,
  `created_by` VARCHAR(128) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `uk_programmatic_dsp_snapshot_daily` (`tenant_id`, `seat_id`, `campaign_id`, `line_item_id`, `snapshot_date`),
  KEY `idx_programmatic_dsp_snapshot_scope` (`tenant_id`, `snapshot_date`, `seat_id`, `campaign_id`),
  KEY `idx_programmatic_dsp_snapshot_line_item` (`tenant_id`, `line_item_id`, `snapshot_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Programmatic DSP daily delivery and performance snapshots';
