CREATE TABLE IF NOT EXISTS `marketing_monitor_anomaly_rule` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `tenant_id` BIGINT NOT NULL,
  `rule_key` VARCHAR(128) NOT NULL,
  `display_name` VARCHAR(255) NOT NULL,
  `source_id` BIGINT NULL,
  `metric_key` VARCHAR(64) NOT NULL,
  `bucket_grain` VARCHAR(16) NOT NULL DEFAULT 'DAY',
  `brand_key` VARCHAR(128) NOT NULL DEFAULT '',
  `competitor_key` VARCHAR(128) NOT NULL DEFAULT '',
  `direction` VARCHAR(16) NOT NULL DEFAULT 'BOTH',
  `baseline_window_buckets` INT NOT NULL DEFAULT 14,
  `min_baseline_buckets` INT NOT NULL DEFAULT 5,
  `threshold_multiplier` DECIMAL(10,4) NOT NULL DEFAULT 3.0000,
  `min_delta` DECIMAL(18,6) NOT NULL DEFAULT 1.000000,
  `enabled` TINYINT NOT NULL DEFAULT 1,
  `metadata_json` JSON NULL,
  `created_by` VARCHAR(128) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `uk_monitor_anomaly_rule_key` (`tenant_id`, `rule_key`),
  KEY `idx_monitor_anomaly_rule_scope` (`tenant_id`, `source_id`, `metric_key`, `enabled`),
  KEY `idx_monitor_anomaly_rule_updated` (`tenant_id`, `updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Marketing monitoring anomaly detection rules';

CREATE TABLE IF NOT EXISTS `marketing_monitor_anomaly_event` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `tenant_id` BIGINT NOT NULL,
  `rule_id` BIGINT NOT NULL,
  `rule_key` VARCHAR(128) NOT NULL,
  `source_id` BIGINT NOT NULL DEFAULT 0,
  `source_key` VARCHAR(128) NULL,
  `metric_key` VARCHAR(64) NOT NULL,
  `bucket_grain` VARCHAR(16) NOT NULL DEFAULT 'DAY',
  `bucket_start` DATETIME NOT NULL,
  `bucket_end` DATETIME NOT NULL,
  `brand_key` VARCHAR(128) NOT NULL DEFAULT '',
  `competitor_key` VARCHAR(128) NOT NULL DEFAULT '',
  `actual_value` DECIMAL(18,6) NOT NULL DEFAULT 0.000000,
  `baseline_median` DECIMAL(18,6) NOT NULL DEFAULT 0.000000,
  `baseline_mad` DECIMAL(18,6) NOT NULL DEFAULT 0.000000,
  `robust_z_score` DECIMAL(18,6) NOT NULL DEFAULT 0.000000,
  `delta_value` DECIMAL(18,6) NOT NULL DEFAULT 0.000000,
  `direction` VARCHAR(16) NOT NULL,
  `severity` VARCHAR(16) NOT NULL,
  `status` VARCHAR(16) NOT NULL DEFAULT 'OPEN',
  `evidence_json` JSON NULL,
  `created_by` VARCHAR(128) NULL,
  `resolved_by` VARCHAR(128) NULL,
  `resolved_at` DATETIME NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `uk_monitor_anomaly_event_bucket` (`tenant_id`, `rule_id`, `metric_key`, `source_id`, `brand_key`, `competitor_key`, `bucket_start`),
  KEY `idx_monitor_anomaly_event_status` (`tenant_id`, `status`, `severity`, `bucket_start`),
  KEY `idx_monitor_anomaly_event_rule` (`tenant_id`, `rule_id`, `bucket_start`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Marketing monitoring anomaly detection event evidence';
