CREATE TABLE IF NOT EXISTS marketing_monitor_provider_oauth_authorization (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  tenant_id BIGINT NOT NULL DEFAULT 0,
  auth_state VARCHAR(128) NOT NULL,
  credential_key VARCHAR(128) NOT NULL,
  provider_type VARCHAR(64) NOT NULL,
  auth_type VARCHAR(64) NOT NULL,
  display_name VARCHAR(128) NOT NULL,
  status VARCHAR(64) NOT NULL DEFAULT 'PENDING',
  authorize_endpoint VARCHAR(512) NOT NULL,
  token_endpoint VARCHAR(512) NOT NULL,
  redirect_uri VARCHAR(512) NOT NULL,
  client_id_ciphertext VARCHAR(1000) NOT NULL,
  client_secret_ciphertext VARCHAR(2000) NULL,
  scopes_json JSON NULL,
  code_verifier_ciphertext VARCHAR(1000) NOT NULL,
  code_challenge VARCHAR(256) NOT NULL,
  code_challenge_method VARCHAR(32) NOT NULL DEFAULT 'S256',
  authorize_params_json JSON NULL,
  token_type VARCHAR(64) NULL,
  credential_id BIGINT NULL,
  provider_error VARCHAR(512) NULL,
  provider_error_description VARCHAR(1000) NULL,
  last_http_status INT NULL,
  last_error_message VARCHAR(1000) NULL,
  expires_at DATETIME NOT NULL,
  completed_at DATETIME NULL,
  metadata_json JSON NULL,
  created_by VARCHAR(128) NOT NULL DEFAULT 'system',
  updated_by VARCHAR(128) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_monitor_oauth_authorization_state (auth_state),
  KEY idx_monitor_oauth_authorization_status (tenant_id, provider_type, status, expires_at),
  KEY idx_monitor_oauth_authorization_credential (tenant_id, credential_key, created_at),
  KEY idx_monitor_oauth_authorization_updated (tenant_id, updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='OAuth authorization-code onboarding state for marketing monitoring provider credentials';

CREATE TABLE IF NOT EXISTS marketing_monitor_provider_oauth_authorization_event (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  tenant_id BIGINT NOT NULL DEFAULT 0,
  authorization_id BIGINT NOT NULL,
  auth_state VARCHAR(128) NOT NULL,
  credential_key VARCHAR(128) NOT NULL,
  event_type VARCHAR(64) NOT NULL,
  status VARCHAR(64) NOT NULL,
  metadata_json JSON NULL,
  error_message VARCHAR(1000) NULL,
  created_by VARCHAR(128) NOT NULL DEFAULT 'system',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_monitor_oauth_authorization_event (tenant_id, authorization_id, created_at),
  KEY idx_monitor_oauth_authorization_event_type (tenant_id, event_type, status, created_at),
  KEY idx_monitor_oauth_authorization_event_state (tenant_id, auth_state, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Lifecycle events for monitoring provider OAuth authorization attempts';
