CREATE TABLE IF NOT EXISTS marketing_asset_upload_intent (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  tenant_id BIGINT NOT NULL,
  intent_key VARCHAR(128) NOT NULL,
  asset_key VARCHAR(128) NOT NULL,
  asset_type VARCHAR(32) NOT NULL,
  provider VARCHAR(32) NOT NULL,
  mime_type VARCHAR(128) NOT NULL,
  file_name VARCHAR(255) NULL,
  size_bytes BIGINT NULL,
  upload_token VARCHAR(128) NOT NULL,
  upload_url VARCHAR(512) NOT NULL,
  upload_params_json JSON NOT NULL,
  status VARCHAR(32) NOT NULL,
  provider_asset_id VARCHAR(255) NULL,
  callback_json JSON NULL,
  error_message TEXT NULL,
  expires_at DATETIME NOT NULL,
  created_by VARCHAR(128) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_marketing_asset_upload_intent_key (tenant_id, intent_key),
  UNIQUE KEY uk_marketing_asset_upload_token (tenant_id, upload_token),
  INDEX idx_marketing_asset_upload_asset (tenant_id, asset_key, status),
  INDEX idx_marketing_asset_upload_provider_asset (tenant_id, provider, provider_asset_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
