CREATE TABLE `delivery_outbox` (
  `id`                     BIGINT        NOT NULL AUTO_INCREMENT,
  `tenant_id`              BIGINT        NOT NULL DEFAULT 1,
  `message_send_record_id` BIGINT        NOT NULL,
  `execution_id`           VARCHAR(64)   NOT NULL,
  `canvas_id`              BIGINT        NOT NULL,
  `user_id`                VARCHAR(128)  NOT NULL,
  `node_id`                VARCHAR(64)   NOT NULL,
  `channel`                VARCHAR(32)   NOT NULL,
  `provider`               VARCHAR(64)   NOT NULL,
  `payload_json`           JSON          NULL,
  `idempotency_key`        VARCHAR(255)  NOT NULL,
  `status`                 VARCHAR(32)   NOT NULL,
  `attempt_count`          INT           NOT NULL DEFAULT 0,
  `next_retry_at`          DATETIME      NULL,
  `locked_by`              VARCHAR(128)  NULL,
  `locked_at`              DATETIME      NULL,
  `provider_message_id`    VARCHAR(128)  NULL,
  `provider_response_json` JSON          NULL,
  `last_error`             VARCHAR(500)  NULL,
  `created_at`             DATETIME      NOT NULL,
  `updated_at`             DATETIME      NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_delivery_outbox_tenant_idempotency` (`tenant_id`, `idempotency_key`),
  KEY `idx_delivery_outbox_status_retry` (`status`, `next_retry_at`, `id`),
  KEY `idx_delivery_outbox_execution` (`execution_id`, `node_id`),
  KEY `idx_delivery_outbox_user` (`tenant_id`, `user_id`, `created_at`),
  KEY `idx_delivery_outbox_provider_message` (`provider`, `provider_message_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Crash-safe channel delivery outbox';

CREATE TABLE `delivery_receipt_log` (
  `id`                  BIGINT        NOT NULL AUTO_INCREMENT,
  `tenant_id`           BIGINT        NOT NULL DEFAULT 1,
  `outbox_id`           BIGINT        NOT NULL,
  `provider`            VARCHAR(64)   NOT NULL,
  `provider_message_id` VARCHAR(128)  NOT NULL,
  `receipt_type`        VARCHAR(64)   NOT NULL,
  `raw_payload_json`    JSON          NULL,
  `idempotency_key`     VARCHAR(255)  NOT NULL,
  `received_at`         DATETIME      NOT NULL,
  `created_at`          DATETIME      NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_delivery_receipt_tenant_idempotency` (`tenant_id`, `idempotency_key`),
  KEY `idx_delivery_receipt_outbox` (`outbox_id`, `received_at`),
  KEY `idx_delivery_receipt_provider_message` (`provider`, `provider_message_id`, `received_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Provider delivery receipt history';
